### ISSUE TITLE
Compute:  Ddv4 and Ddsv4 VM sizes missing

### ISSUE THREAD

**Issue by jrottenberg** [Azure/azure-rest-api-specs#9995] opened 2020-06-30 17:49 UTC
the latest in stable is missing the Ddv4 and Ddsv4-series

For example, I have those instances type deployed : 

- Standard_D2ds_v4
- Standard_D4ds_v4

but they are missing in the spec :
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-06-01/compute.json

https://docs.microsoft.com/en-us/azure/virtual-machines/ddv4-ddsv4-series

Thank you.

**Comment by Drewm3** [comment] 2020-08-13 16:39
@jrottenberg, are you referring to the list of VM sizes under HardwareProfile in compute.json? New sizes are not going to be added to this file. We are in the process of changing the file going forward to remove the majority of the existing sizes listed in the file in order to be very clear that customers must use the SKUs API to get the list of available sizes for a selected subscription.

The change to the compute.json file is being driven under issue: https://github.com/Azure/azure-rest-api-specs/issues/10033. 

I am going to close this issue because it is effectively a duplicate of [10033](https://github.com/Azure/azure-rest-api-specs/issues/10033).

**Comment by jrottenberg** [comment] 2020-08-17 17:49
@Drewm3 yes I was, indirectly : https://github.com/terraform-linters/tflint-ruleset-azurerm is using the api spec to derive the machine type terraform can use, without having to actually interact with the api (so before a `terraform plan`)

but yeah the author created a bug, better to follow up there.

**Comment by Drewm3** [comment] 2020-08-20 00:18
Opening and reclosing this issue to trigger an update to the Microsoft reporting services.

**Closed** 2020-08-20 00:19 UTC
Labels: Compute, Service Attention, question
