### ISSUE TITLE
Difference in externalDocs description causes Autorest to fail while generating composite client.

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-rest-api-specs#1071] opened 2017-03-26 05:15 UTC
[doc1](https://github.com/Azure/azure-rest-api-specs/blob/dde5294811c862dda262732f348d181846c944f5/arm-apimanagement/2016-10-10/swagger/apimopenidconnectproviders.json#L9) & [doc2](https://github.com/Azure/azure-rest-api-specs/blob/dde5294811c862dda262732f348d181846c944f5/arm-apimanagement/2016-10-10/swagger/apimbackends.json#L9)

Composite Swagger is a mechanism to compose/package multiple swaggers into one client. Hence certain things needs to be same across all the swaggers that need to be packaged into one client.

However, I am not sure if Autorest needs to be so strict on the top level externalDocs. How does that translate to the client documentation? 
/cc @samirsolanki @fearthecowboy @olydis

```
------------------------------------------------------------
autorest -Modeler CompositeSwagger -CodeGenerator Azure.NodeJS -Input https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-apimanagement/compositeApiManagementClient.json  -outputDirectory lib/services/apiManagement/lib -Header MICROSOFT_MIT_NO_VERSION --version=1.0.1-20170324-2300-nightly
------------------------------------------------------------
FATAL: Error generating client model: System.Exception: $.externalDocs.description has incomaptible values (How to authorize developer accounts using OAuth 2.0 in Azure API Management., How to secure an API configured in API Management).
   at AutoRest.Core.Parsing.YamlExtensions.MergeYamlObjects[T](T a, T b, ObjectPath path) in /Users/amarz/sdk/AutoRest/src/core/AutoRest.Core/Parsing/YamlExtensions.cs:line 170
   at AutoRest.Core.Parsing.YamlExtensions.MergeYamlObjects[T](T a, T b, ObjectPath path) in /Users/amarz/sdk/AutoRest/src/core/AutoRest.Core/Parsing/YamlExtensions.cs:line 155
   at AutoRest.Core.Parsing.YamlExtensions.MergeYamlObjects[T](T a, T b, ObjectPath path) in /Users/amarz/sdk/AutoRest/src/core/AutoRest.Core/Parsing/YamlExtensions.cs:line 155
   at AutoRest.Core.Parsing.YamlExtensions.MergeWith(YamlMappingNode self, YamlMappingNode other) in /Users/amarz/sdk/AutoRest/src/core/AutoRest.Core/Parsing/YamlExtensions.cs:line 173
   at AutoRest.CompositeSwagger.CompositeSwaggerModeler.Build() in /Users/amarz/sdk/AutoRest/src/modeler/AutoRest.CompositeSwagger/CompositeSwaggerModeler.cs:line 110
   at AutoRest.Core.AutoRestController.Generate() in /Users/amarz/sdk/AutoRest/src/core/AutoRest.Core/AutoRestController.cs:line 56
```

**Comment by solankisamir** [comment] 2017-03-26 12:46
Since these are separate entities in API Management, we wanted our documentation to be like [doc1](https://docs.microsoft.com/en-us/rest/api/apimanagement/apimanagementrest/azure-api-management-rest-api-backend-entity) and [doc2](https://docs.microsoft.com/en-us/rest/api/apimanagement/apimanagementrest/azure-api-management-rest-api-authorization-server-entity)

**Comment by dsgouda** [comment] 2017-03-29 18:24
Will take a look and respond soon, apologize for the delay.

**Comment by dsgouda** [comment] 2017-03-30 21:32
So it seems like any top level property (externalDocs/info) objects would cause the same issue, which happens [here](https://github.com/Azure/autorest/blob/48accb15598ac478cf4cc751be5ec452a52c9c46/src/core/AutoRest.Core/Parsing/YamlExtensions.cs#L131) @fearthecowboy any thoughts on how we should merge such top level property objects

**Comment by fearthecowboy** [comment] 2017-03-30 21:36
The trouble is, what is the expected behavior? 

You can't possibly merge them; in the composed swagger document there can only be one.

**Comment by dsgouda** [comment] 2017-03-30 22:10
@solankisamir CompositeSwagger is a functionality that simply merges individual semantically similar swagger specs under the hood before generating the client. We ensure top level properties are the same to ensure this. The best solution here would be to have externalDocs point to both the links you have mentioned in all of the swagger specs so the top level properties look exactly the same.
P.S.: This should have failed the Travis CI builds

**Comment by solankisamir** [comment] 2017-04-16 01:26
@amarzavery can you close this issue after verifying

**Comment by kirthik** [comment] 2017-06-09 05:44
@dsgouda - Can we close this issue?

**Comment by dsgouda** [comment] 2017-06-12 16:53
Yes, we (AutoRest and linter folks) have provided a workaround for the issue.

**Closed** 2017-06-12 16:53 UTC
Labels: Api Management, P1
