### ISSUE TITLE
[FEATURE REQ] EngSys - Creating a comparable Data-plane PR Review Workflow diagram in template.

### ISSUE THREAD

**Issue by allenjzhang** [Azure/azure-rest-api-specs#28678] opened 2024-04-12 17:42 UTC
### API Spec link

N/A

### API Spec version

N/A

### Please describe the feature.

ARM PR template currently has a very comprehensive and intuitive workflow diagram to guide spec writer thru the review process. We should have similar ones for DP PR as well.

**Comment by konrad-jamrozik** [comment] 2024-04-16 05:23
Closing as duplicate of:
- https://github.com/Azure/azure-sdk-tools/issues/7925

**Closed by konrad-jamrozik** 2024-04-16 05:23 UTC
Labels: feature-request
