### ISSUE TITLE
New Compute Profile Available

### ISSUE THREAD

**Issue by marstr** [Azure/azure-rest-api-specs#895] opened 2017-01-31 22:05 UTC
As seen in Azure/azure-sdk-for-go#525 authored by @moritzheiber:

> Working with Virtual Machine Scale Sets with Ubuntu using this SDK isn't very easy since it neither allows for Scale Sets to carry extensions, nor, since the compute API is using an outdated version, modification of customData passed to each instance.
However, customData is the only way of passing data to Scale Set instances using the go SDK. This means modifying the customData property will only work if you take down the Scale Set prior to modification.
API version 2016-08-30 does support modification of the customData property and I'ld vouch for a bump in API versions in the compute client, if possible.
//cc @pellepelster @fbernitt

A new Swagger profile needs to be defined to accommodate new functionality in the Azure service.

**Comment by colemickens** [comment] 2017-01-31 22:09
(Hopefully one of these new Compute swaggers will include the MSI-related fields. I have an internal thread about this, but I thought it was worth mentioning here as well)

**Comment by moritzheiber** [comment] 2017-02-01 08:22
Solving this issue would be really helpful because without the newer API specs using Scale Sets is pretty much impossible to get right through the dependent SDKs

**Comment by amarzavery** [comment] 2017-02-01 16:12
@huangpf
Please take a look.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by huangpf** [comment] 2017-02-01 17:06
```2016-08-30``` doesn't seem to be an official API version. Is it for a special or preview release or internal customers?

**Comment by moritzheiber** [comment] 2017-02-01 17:08
I was referencing [this support thread](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/2e81dd6a-1741-48aa-ab02-fc5c8c4450c1/how-to-update-vm-scale-sets-customdata-without-down-time?forum=WAVirtualMachinesforWindows#ed3246c3-2109-4443-881c-2da88705a908) in my issue submitted for the Golang SDK.

**Comment by huangpf** [comment] 2017-02-01 17:14
From the Compute spec, you can see there is no such official API version:
https://github.com/Azure/azure-rest-api-specs/tree/master/arm-compute

But I believe AutoRest generated API in any language supports overriding the request being sent, please refer to how this C# handler is defined:
https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/Compute/Compute.Tests/Helpers/RecordedDelegatingHandler.cs

I don't think we have a plan to add a spec with that API version, but I would like to add @singhkays to help confirm.

**Comment by moritzheiber** [comment] 2017-02-01 17:17
So you're saying there is an API version, but it's unofficial, thus there will be no support inside the official SDKs?

**Comment by huangpf** [comment] 2017-02-01 17:35
This needs service team's confirmation, awaiting @singhkays.

**Comment by singhkays** [comment] 2017-02-01 18:29
Sorry @huangpf, I don't own this. From the linked support thread looks like @gbowerman might have some knowledge of this re:VMSS. Also adding @stephbaron for Compute spec question.

**Comment by moritzheiber** [comment] 2017-02-01 20:01
To provide some context: Asking the `AzureCloud` itself, i.e. the providers available and their respective API versions returns the following snippet for `virtualMachineScaleSets`:

```json
{
  "aliases": null,
    "apiVersions": [
      "2016-08-30",
    "2016-03-30",
    "2015-06-15",
    "2015-05-01-preview"
    ],
    "locations": [
      "East US",
    "East US 2",
    "West US",
    "Central US",
    "North Central US",
    "South Central US",
    "North Europe",
    "West Europe",
    "East Asia",
    "Southeast Asia",
    "Japan East",
    "Japan West",
    "Australia East",
    "Australia Southeast",
    "Brazil South",
    "Canada Central",
    "Canada East",
    "West US 2",
    "West Central US",
    "UK South",
    "UK West"
      ],
      "properties": null,
      "resourceType": "virtualMachineScaleSets"
}
```

That's why I was expecting these specs to support the API version I mentioned.

**Comment by gbowerman** [comment] 2017-02-02 18:50
The currently valid Compute API versions are: 2016-03-30 and 2016-04-30-preview.
Despite the preview moniker the latter will be one we recommend to use in production starting next week (2/8). A little while after that it will be 2017-03-30. Therefore the AzureCloud API should return these values (and possibly the 2016-06-15 one as well though I hope no-one uses it since it was before scale set GA).

**Comment by moritzheiber** [comment] 2017-02-02 18:58
@gbowerman Okay, I understand. Two questions though:

1. Why is the API returning the (supposedly unsupported) version `2016-08-30` as "available" then?
2. Why do you recommend using version `2016-08-30` in the linked support thread?
3. Shouldn't the SDK not be a representation of what's available, and not what's recommended? I mean, it's not like your target audience are toddlers .. ?

I'm not trying to be obnoxious here, but the feature I'm after is only supported by the newer API version, and, according to the Azure API, it seems like it's supposed to be supported, thus I was looking for support in the official SDK as well. 

Am I missing something? Just trying to make sense of it.

**Comment by gbowerman** [comment] 2017-02-02 19:01
@moritzheiber as I understand it, 1, 2, 3 above are bugs we need to fix. Your questions are not obnoxious. They are a useful elucidation of the problem.

**Comment by hassanbabaie** [comment] 2017-02-08 16:21
@gbowerman Hi Guy, it doesn't look like Microsoft's API documentation has changed, do you know if the move to 2016-04-30-preview is delayed?

**Comment by gbowerman** [comment] 2017-02-08 22:16
@hassanbabaie 2016-04-30-preview is GA today. Hopefully you'll see the API updated shortly.

**Comment by hassanbabaie** [comment] 2017-02-10 06:29
@gbowerman yes spotted it now, thanks!

**Comment by kirthik** [comment] 2017-02-15 20:11
@gbowerman , @stephbaron : Please close this if the issue is resolved.

**Comment by moritzheiber** [comment] 2017-02-15 21:32
Err, how's 2016-04-30-preview going GA solving this issue? I will still be unable to use Scale Sets properly ..

**Comment by cberner** [comment] 2017-04-05 18:02
It looks like `2017-03-30` has been released, could that be added? We're still blocked on using Scale Sets because the custom_data field can't be modified under the `2016-04-30-preview` API version.

```
> az provider list
...
"apiVersions": [
          "2017-03-30",
          "2016-08-30",
          "2016-04-30-preview",
          "2016-03-30",
          "2015-06-15",
          "2015-05-01-preview"
        ],
```

**Comment by salameer** [comment] 2018-10-09 00:51
Closing due to inactivity

**Closed by salameer** 2018-10-09 00:51 UTC
Labels: Compute, P1, Service Attention
