### ISSUE TITLE
Budgets API is not maintaining case on dictionary keys

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-rest-api-specs#8183] opened 2020-01-17 12:38 UTC
Original issue: https://github.com/Azure/azure-sdk-for-go/issues/5418

```
PUT https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myTest/providers/Microsoft.Consumption/budgets/myBudget?api-version=2019-01-01
```
Request body:
```
{
    "properties": {
        "amount": "100.65",
        "category": "Cost",
        "filters": {
            "meters": [
                "00000000-0000-0000-0000-000000000000"
            ],
            "resources": [
                "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myTest/providers/Microsoft.Compute/virtualMachineScaleSets/myVmss"
            ],
            "tags": {
                "CATEGORY": [
                    "Dev",
                    "Prod"
                ],
                "DEPARTMENT": [
                    "engineering",
                    "sales"
                ]
            }
        },
        "notifications": {
            "TEST_NOTIFICATION": {
                "enabled": true,
                "operator": "GreaterThan",
                "threshold": "80.12",
                "contactEmails": [
                    "andrew.brown@nowhere.com"
                ]
            }
        },
        "timeGrain": "Monthly",
        "timePeriod": {
            "startDate": "2020-02-01T00:00:00Z",
            "endDate": "2022-10-31T00:00:00Z"
        }
    }
}
```
And received response are:
```
{
    "id": "subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myTest/providers/Microsoft.Consumption/budgets/myBudget",
    "name": "myBudget",
    "type": "Microsoft.Consumption/budgets",
    "eTag": "\"1d5cd321c846b6b\"",
    "properties": {
        "timePeriod": {
            "startDate": "2020-02-01T00:00:00Z",
            "endDate": "2022-10-31T00:00:00Z"
        },
        "timeGrain": "Monthly",
        "amount": 100.65,
        "currentSpend": null,
        "category": "Cost",
        "notifications": {
            "tesT_NOTIFICATION": {
                "enabled": true,
                "operator": "GreaterThan",
                "threshold": 80.1200,
                "contactEmails": [
                    "andrew.brown@nowhere.com"
                ],
                "contactRoles": [],
                "contactGroups": [],
                "thresholdType": "Actual"
            }
        },
        "filters": {
            "resourceGroups": [],
            "resources": [
                "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myTest/providers/Microsoft.Compute/virtualMachineScaleSets/myVmss"
            ],
            "meters": [
                "00000000-0000-0000-0000-000000000000"
            ],
            "tags": {
                "category": [
                    "Dev",
                    "Prod"
                ],
                "department": [
                    "engineering",
                    "sales"
                ]
            }
        }
    }
}
```
Note that the first 3 letters of the notification key have been mutated to lower cases and the filter tag keys have been all turn to low cases.
These changes may break some tools such as terraform.

**Comment by ArcturusZhang** [comment] 2020-01-18 06:59
Hi @ms-premp @bgsky could you please have a look at this issue?

**Comment by ms-premp** [comment] 2020-06-28 09:40
This is by design.

**Comment by ramaganesan-rg** [comment] 2020-06-29 00:25
Closing this, as its by-design.

**Closed by ramaganesan-rg** 2020-06-29 00:25 UTC
Labels: Consumption, Service Attention, bug
