### ISSUE TITLE
Resource manager statusMessage property has incorrect type.

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-rest-api-specs#2355] opened 2018-01-29 18:17 UTC
In https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2017-05-10/resources.json#L2068.  The property statusMessage is defined as object however the service doesn't always return an object (sometimes a string).  This results in broken behavior for the Go SDK.  The type must be either a string or an object and the service must abide by the specified contract.  See https://github.com/Azure/azure-sdk-for-go/issues/938 for more details.

**Comment by jhendrixMSFT** [comment] 2018-02-13 17:28
After recent discoveries in JSON schema I believe the correct thing to do here is remove the "type" so that statusMessage is treated as a wildcard type.  @olydis @fearthecowboy do you agree?

**Comment by fearthecowboy** [comment] 2018-02-13 17:32
I believe that should be the case; I think we're still waiting for everyone to fix the generators to get the right behavior everywhere.

**Comment by jhendrixMSFT** [comment] 2018-02-13 17:42
Do we need to wait for that before updating the swagger?

**Comment by fearthecowboy** [comment] 2018-02-13 17:55
@olydis  is going to verify that there isn't any breaking change to the code model if you do this now.

**Comment by olydis** [comment] 2018-02-13 18:09
Confirmed: The current modeler (the one that does *not* handle object types properly) generates identical output for `type: object` vs no `type` on `statusMessage`, so indeed it can be safely removed without inducing breaking changes across existing generators. That was what my assumption, but wanted to confirm 😋

**Comment by zhenglaizhang** [comment] 2020-12-29 07:21
Looks like the issue is fixed in https://github.com/Azure/azure-rest-api-specs/pull/2486, I will close it, if any guys has concern or questions, pls reopen it. thanks!

**Closed by zhenglaizhang** 2020-12-29 07:21 UTC
