### ISSUE TITLE
web: type error in sslState in HostNameSslState class

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#141] opened 2016-02-18 20:14 UTC
Hello,

I work in the MS Azure Python SDK team and I'm currently trying the Autorest generated version for Python,
I'm just trying to do a `get` a a website using webspace+name using this Python SDK generated from the Web Swagger file (rev. c81ae63ef1dc19b3d366e5c9cfc5a10925d59e04) with the `"Sites_GetSite` method.
I got in result for `hostNameSslStates`

``` json
    "hostNameSslStates": [
      {
        "name": "mysite.azurewebsites.net",
        "sslState": 0,
        "ipBasedSslResult": null,
        "virtualIP": null,
        "thumbprint": null,
        "toUpdate": null,
        "toUpdateIpBasedSsl": null,
        "ipBasedSslState": 0,
        "hostType": 0
      },
```

Regarding the Swagger spec, "sslState" is an enum:

``` json
"sslState": {
          "description": "SSL type",
          "enum": [
            "Disabled",
            "SniEnabled",
            "IpBasedEnabled"
          ],
          "type": "string",
          "x-ms-enum": {
            "name": "SslState",
            "modelAsString": false
          }
        },
```

However, as you can see the `sslState` I got is 0, not a string.

It's the second bug (after https://github.com/Azure/azure-rest-api-specs/issues/137) I open on the web file so far, is this possible to have at least a confirmation or state from the web team about this?
Thank you,

**Comment by amarzavery** [comment] 2016-02-19 19:47
@naveedaz - Can you please take a look into this issue?

**Comment by amarzavery** [comment] 2016-02-19 22:21
@lmazuel 
I have no clue why is the server sending you `0` instead of one of the valid values. This definitely is a bug on the server side. Either the spec needs to be updated or the server side needs a fix.

From code gen point of view, the extension "x-ms-enum" is documented over [here](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/creating-swagger.md#Enum-x-ms-enum). 
Since "modelAsString" is set to false, sslState would be an enum in C# and Java. Node.js does not support enums. The generated node.js code will do the validation (throw if the value is not from the set of valid values) in this case.

I am not sure about Python. v3.4 has enums implemented and v2.7 does not. 
@xingwu1 who implemented the python code gen would be in a better position to comment on the behavior in python.

**Comment by amarzavery** [comment] 2016-02-19 22:26
@lmazuel - Update to my comment:
Sorry, I concluded too fast. Is this the response from the server or the deserialized response from the python code gen? If the server is sending the correct response (string for sslState) then Python codegen is doing something different (Returning index of the enumValue)..

**Comment by lmazuel** [comment] 2016-02-19 22:30
This is the actual response from the server, I know it's important to check that this is not a language specific problem. No Python here :)

**Comment by lmazuel** [comment] 2016-02-19 22:31
> Either the spec needs to be updated or the server side needs a fix.

It's what I think too.

**Comment by amarzavery** [comment] 2016-02-19 22:34
Thanks for confirming. Then this is a server side issue. @naveedaz from webapps team would be in a better position to comment.

**Comment by amarzavery** [comment] 2016-02-24 20:32
@naveedaz - Any update on this?

**Comment by naveedaz** [comment] 2016-02-24 23:47
From Microsoft.Web standpoint the response has enumerations as proper enumtypes like for SSLState: Disabled, SniEnabled, IpBasedEnabled etc. 
However the requests are brokered from user to resource provider by Azure resource Manager, and the response from there seems to have 0,1,2 instead of the enum types. 
@IlyaGrebnov Can you elaborate on why that is the case?

**Comment by IlyaGrebnov** [comment] 2016-02-25 06:23
@naveedaz ARM doesn't know schema of individual resources, so maping "string" to int (and vise-versa) is not possible at our layer. Most likely issue is caused by Microsoft.Web RP or client tools/libs.

**Comment by lmazuel** [comment] 2016-02-25 17:49
@naveedaz @IlyaGrebnov I can assure you that this it NOT a client tools/libs problem: the answer I got is direct from the REST API.

**Comment by IlyaGrebnov** [comment] 2016-02-25 22:43
Yes, I believe this is know bug in Antares/Geomaster RP which serialize enums to numbers by default.

**Comment by lmazuel** [comment] 2016-03-08 22:31
Any news on this one?

I made a screenshot of resources.azure.com to establish at 100% that this is not a Python issue
![sslstatebug](https://cloud.githubusercontent.com/assets/1050156/13618686/5e858486-e53a-11e5-923a-14b653223542.png)

**Comment by lmazuel** [comment] 2016-03-16 00:25
@IlyaGrebnov @naveedaz Is this possible to have a status on this one?
For now, it was "just" internally by me but now I have an open bug which related to this one (https://github.com/Azure/azure-sdk-for-python/issues/544)

At least a status: we will fix it, we won't, you will need a new API version, there is an open issue there http://xxxx, etc.
Another guy in our team had to patch his code manually to do his //Build demo.
There is no workaround since the JSON exposed by the API uses an index from an enum we don't know (we have no guarantee that the enum order in the Swagger file is the one considered by the server).

Thank you for considering this.

**Comment by IlyaGrebnov** [comment] 2016-03-16 22:45
@naveedaz could you please comment on this? ARM simple proxy response from resource provider. And I believe this is issue on 'GeoMester'.

**Comment by devigned** [comment] 2016-05-02 17:40
@naveedaz are there any plan to correct this issue, or should we expect the API to continue to return the integer response?

If we are to expect the API to return the integer response, can you then ensure that any new enums will be added to the end of the list, thus preserving the correctness of the generated code? Any change to the order of the enumeration will be a breaking change to end users.

/cc @kamaljit for visibility.

**Comment by amarzavery** [comment] 2016-10-05 21:03
@naveedaz - It has been open for more than 6 months now. Any ETA for this fix?

**Comment by garimakhulbe** [comment] 2016-10-11 22:17
@naveedaz Any status on this?

**Comment by naveedaz** [comment] 2016-10-12 17:57
We are working on a fix targeted for next release ETA end of month. The fix will be api-version specific to prevent breaking existing clients.

**Comment by jhendrixMSFT** [comment] 2016-10-12 18:02
Thanks for the update, will that fix include the issue mentioned in https://github.com/Azure/azure-rest-api-specs/issues/137?

**Comment by naveedaz** [comment] 2016-10-12 20:43
Yes. It will address that issue as well.

**Comment by jhendrixMSFT** [comment] 2016-10-27 19:25
@naveedaz Is this still on track to be fixed by the end of this month?

**Comment by naveedaz** [comment] 2016-10-27 19:35
@jhendrixMSFT The fix was checked in 10/13/2016. However, we hit some bumps with our deployment train and is now targeted for Nov 11 2016. Users will have to use api-version >= 2016-08-01. The latest composite swagger files have the updated api versions. https://github.com/Azure/azure-rest-api-specs/blob/master/arm-web/compositeWebAppClient.json.

**Comment by naveedaz** [comment] 2016-11-17 01:00
FYI the fix is deployed. Users will have to use api-version >= 2016-08-01. The latest composite swagger files have the updated api versions. https://github.com/Azure/azure-rest-api-specs/blob/master/arm-web/compositeWebAppClient.json. 

"hostNameSslStates": [
      {
        "name": "naveedalb.trafficmanager.net",
        "sslState": "Disabled",
        "ipBasedSslResult": null,
        "virtualIP": null,
        "thumbprint": null,
        "toUpdate": null,
        "toUpdateIpBasedSsl": null,
        "ipBasedSslState": "NotConfigured",
        "hostType": "Standard"
      },
      {
        "name": "naveedasrc.azurewebsites.net",
        "sslState": "Disabled",
        "ipBasedSslResult": null,
        "virtualIP": null,
        "thumbprint": null,
        "toUpdate": null,
        "toUpdateIpBasedSsl": null,
        "ipBasedSslState": "NotConfigured",
        "hostType": "Standard"
      },
      {
        "name": "naveedasrc.scm.azurewebsites.net",
        "sslState": "Disabled",
        "ipBasedSslResult": null,
        "virtualIP": null,
        "thumbprint": null,
        "toUpdate": null,
        "toUpdateIpBasedSsl": null,
        "ipBasedSslState": "NotConfigured",
        "hostType": "Repository"
      }
    ]

**Closed** 2016-11-18 21:45 UTC
