### ISSUE TITLE
[HDInsight] `KafkaRestProperties` should not require `groupName` given `groupId` has been specified

### ISSUE THREAD

**Issue by magodo** [Azure/azure-rest-api-specs#10667] opened 2020-09-02 03:00 UTC
The [`ClientGroupInfo`](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/hdinsight/resource-manager/Microsoft.HDInsight/stable/2018-06-01-preview/cluster.json#L643) property already accept a `groupId` in request body, based on which service should be able to deduce the `groupName`. This issue suggest to remove the `groupName` from the model as an input property.

**Comment by aim-for-better** [comment] 2020-09-08 02:07
Hi @magodo , This is by design, This property not only as input but also as output. Please see [here](https://github.com/Azure/azure-rest-api-specs/blob/ddfe040e320a928c1a3cec4e7a4024ff448c6a4c/specification/hdinsight/resource-manager/Microsoft.HDInsight/stable/2018-06-01-preview/cluster.json#L1197), This property will return to customer  when they call Get cluster API.

**Comment by aim-for-better** [comment] 2020-09-08 02:10
> Hi @magodo , This is by design, This property not only as input but also as output. Please see [here](https://github.com/Azure/azure-rest-api-specs/blob/ddfe040e320a928c1a3cec4e7a4024ff448c6a4c/specification/hdinsight/resource-manager/Microsoft.HDInsight/stable/2018-06-01-preview/cluster.json#L1197), This property will return to customer when they call Get cluster API.

Returning group name is more readable for customer.

Could you please share more about this issue? For example, what's the impact on you?

**Comment by magodo** [comment] 2020-09-08 05:24
As the API consumer, it is more handy to provide the least amout of input in request. In this case, `groupName` can be deduced from `groupId`, which seems redundent to ask users to also specify. Otherwise, making `groupName` as output only (`readOnly`) might be a better choice here.

Specifically, I'm working on this feature in Terraform azurerm provider. Look at this comment: https://github.com/terraform-providers/terraform-provider-azurerm/pull/8064#discussion_r480079072

**Comment by deshriva** [comment] 2020-09-18 02:34
@magodo : Thanks for the feedback. We have opened a work item and plan to address it in a future release.

**Comment by deshriva** [comment] 2020-10-25 01:39
@magodo : Can we close this request, we have a work item and this change will be rolled out with a new API version.

**Comment by magodo** [comment] 2020-10-26 01:51
@deshriva Thank you for the update, can we wait until the Swagger PR for that new API version is merged?

**Comment by aim-for-better** [comment] 2020-11-24 02:00
Thanks for the feedback. We have opened a work item and plan to address it in a future release.

**Comment by aim-for-better** [comment] 2020-12-21 05:35
on going

**Comment by aim-for-better** [comment] 2021-01-12 08:47
on going

**Comment by aim-for-better** [comment] 2021-02-05 07:44
on going

**Comment by aim-for-better** [comment] 2021-03-02 07:03
on going

**Closed** 2021-03-26 03:26 UTC
Labels: HDInsight, Service Attention, question
