### ISSUE TITLE
[BluePrint] [APIissue] resource type name blueprintAssignment/{name}/operations should be chnaged to /assignmentOperations

### ISSUE THREAD

**Issue by ravbhatnagar** [Azure/azure-rest-api-specs#4903] opened 2018-12-12 21:13 UTC
As per discussion with Marcin, below is the proposal -
/assignmentOperations
In a resource ID, it will look like this /subscriptions/{id}/providers/Microsoft.Blueprint/blueprintAssignments/{name}/assignmentOperations, which is redundant. On the upside the generated SDK already calls this object AssignmentOperations, so it will match the API now. The downside is that we will continue supporting /operations on API version 2017-11-11-*. API versions 2018-11-01-* and later would use /assignmentOperations. This will remain in our RP manifest and service code until 2017-11-11-preview is fully deprecated and removed. This seems like a good compromise to get this PR unblocked.

**Comment by haitch** [comment] 2018-12-12 23:57
this is addressed in [latest commit](https://github.com/Azure/azure-rest-api-specs/pull/4590/commits/1208b90b526f3872c07ae9d9a91646102b94e0a3)

**Comment by amarzavery** [comment] 2018-12-13 01:49
Looks Like the issue is addressed in PR #4590. Since @annatisch is already reviewing the PR, assigning the issue to her as she will have more context on this.

**Comment by majastrz** [comment] 2019-12-11 19:20
This has been implemented for a while now. Closing the issue.

**Closed by majastrz** 2019-12-11 19:20 UTC
Labels: ARM-Review-Issue
