### ISSUE TITLE
[DataLake Store - filesystem api-version: 2015-10-01] Semantic validation fails with duplicate API path errors

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-rest-api-specs#801] opened 2016-12-15 01:34 UTC
/azure-rest-api-specs/arm-datalake-store/filesystem/2015-10-01-preview/swagger/filesystem.json

Errors
------
DUPLICATE_API_PATH : #/paths//webhdfs/v1/{destinationPath} : API path (or equivalent) already defined: /webhdfs/v1/{destinationPath}
DUPLICATE_API_PATH : #/paths//webhdfs/v1/{msConcatDestinationPath} : API path (or equivalent) already defined: /webhdfs/v1/{msConcatDestinationPath}
DUPLICATE_API_PATH : #/paths//webhdfs/v1/{listFilePath} : API path (or equivalent) already defined: /webhdfs/v1/{listFilePath}
DUPLICATE_API_PATH : #/paths//webhdfs/v1/{getFilePath} : API path (or equivalent) already defined: /webhdfs/v1/{getFilePath}
DUPLICATE_API_PATH : #/paths//webhdfs/v1/{flushFilePath} : API path (or equivalent) already defined: /webhdfs/v1/{flushFilePath}
DUPLICATE_API_PATH : #/paths//webhdfs/v1/{directFilePath} : API path (or equivalent) already defined: /webhdfs/v1/{directFilePath}
DUPLICATE_API_PATH : #/paths//webhdfs/v1/{setAclFilePath} : API path (or equivalent) already defined: /webhdfs/v1/{setAclFilePath}
DUPLICATE_API_PATH : #/paths//webhdfs/v1/{modifyAclFilePath} : API path (or equivalent) already defined: /webhdfs/v1/{modifyAclFilePath}
DUPLICATE_API_PATH : #/paths//webhdfs/v1/{removeAclFilePath} : API path (or equivalent) already defined: /webhdfs/v1/{removeAclFilePath}
DUPLICATE_API_PATH : #/paths//webhdfs/v1/{defaultAclFilePath} : API path (or equivalent) already defined: /webhdfs/v1/{defaultAclFilePath}
DUPLICATE_API_PATH : #/paths//webhdfs/v1/{aclFilePath} : API path (or equivalent) already defined: /webhdfs/v1/{aclFilePath}
DUPLICATE_API_PATH : #/paths//webhdfs/v1/{filePath} : API path (or equivalent) already defined: /webhdfs/v1/{filePath}
DUPLICATE_API_PATH : #/paths//webhdfs/v1/{renameFilePath} : API path (or equivalent) already defined: /webhdfs/v1/{renameFilePath}
DUPLICATE_API_PATH : #/paths//webhdfs/v1/{setOwnerFilePath} : API path (or equivalent) already defined: /webhdfs/v1/{setOwnerFilePath}
DUPLICATE_API_PATH : #/paths//webhdfs/v1/{setPermissionFilePath} : API path (or equivalent) already defined: /webhdfs/v1/{setPermissionFilePath}

**Comment by begoldsm** [comment] 2017-02-16 16:56
@veronicagg this is by design. There is no way in swagger today, that I am aware of, to differentiate methods by query parameters. Each of these paths behaves differently based on a query parameter (which then also results in different requests/responses and parameters being passed in to the call). If there is some other way to make "unique" paths that include a static query parameter, I can make the change, otherwise this will have to remain.

**Comment by begoldsm** [comment] 2017-03-24 18:04
@veronicagg please close this, we are not going to fix the 2015-10-01-preview swagger API as we have moved on to the latest 2016-11-01. I have a PR out to remove all of our preview swagger specs now.

**Closed** 2017-06-09 06:28 UTC
Labels: Data Lake, internal-ms, P1
