### ISSUE TITLE
Dedicated Host Group: ResourceGroup name has wrong case

### ISSUE THREAD

**Issue by magodo** [Azure/azure-rest-api-specs#8068] opened 2020-01-04 11:25 UTC
While working on a new terraform resource for a Dedicated Host Group ( terraform-providers/terraform-provider-azurerm#5048 ) I stumbled across an issue with upper case resource group names.

## Step to reproduce:

- create a resource group named `magodo-rg`
- create a dedicated host group in this resource group

API request: `https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/magodo-rg/providers/Microsoft.Compute/hostGroups/magodo_host_group?api-version=2019-03-01`

The API response for the dedicated host group resource is like:

```
{
  "name": "magodo_host_group",
  "id": "/subscriptions/{{subscriptionId}}/resourceGroups/MAGODO-RG/providers/Microsoft.Compute/hostGroups/magodo_host_group",
  "location": "eastus2",
  "properties": {
    "platformFaultDomainCount": 1
  }
}
```
The problem is that the resource group is uppercased in the id attribute.

## Expected Behaviour:

Having an id with resource group name `magodo-rg`.
This is the behaviour when creating most other resources in azure.

**Comment by Drewm3** [comment] 2020-01-15 05:58
This is by design in the Microsoft.compute resource provider. I understand that this different behavior from many other resource providers, but it is an allowed behavior based on the Azure Resource Provider specification. The Microsoft.compute resource provider team has investigated the work to always return the casing of the RG based on the first time it "sees" the RG, but this would be a very big change in the compute resource provider. At this time the team is not planning to make this rather large investment especially considering that the first time the compute resource provider "sees" the resource group name it may or maynot be the "correct" casing for the resource group. The reason for this is that technically only the top level Azure Resource Provider knows the "correct" casing of the resource group because only that service sees the very first "Create Resource Group" API which should technically define the "correct" casing for the RG. All other resources providers that create resources in that RG only see the casing as provided by the API caller when the resource in the resource group is created for the first time.

**Comment by Drewm3** [comment] 2020-01-15 05:59
Closing because this is the expected behavior currently.

**Comment by tombuildsstuff** [comment] 2020-01-15 06:53
@Drewm3 thanks for confirming that this is a bug in the API - can we re-open this issue to track fixing this bug in a future API version? Thanks!

**Comment by erich-wang** [comment] 2020-01-21 03:12
reopen this issue per comment from @tombuildsstuff, and assign back to @ArcturusZhang

**Comment by Drewm3** [comment] 2020-02-09 23:26
@tombuildsstuff, this behavior is by design in the API. It is not a bug. Feel free to open a feature request in UserVoice for a design change (aka feature).

**Closed by Drewm3** 2020-02-09 23:26 UTC
Labels: Compute, Mgmt, Service Attention
