### ISSUE TITLE
Broken schema reference

### ISSUE THREAD

**Issue by MWL88** [Azure/azure-rest-api-specs#13197] opened 2021-02-28 21:18 UTC
The schema reference [here](https://github.com/Azure/azure-rest-api-specs/blob/057a2f0ecad93bf837e6299b3b0393bc662cbbd7/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2020-12-01/examples/ApiManagementCreateContentType.json#L15) is not correct and cannot be resolved.

This occurs when loading `specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2020-12-01/apimcontenttypes.json`.

[This](https://github.com/MWL88/azure-rest-api-specs/commit/c5428b51873aeaae3b28e4e2e2ae82959b2983b5) appears the fix the issue.

**Comment by raych1** [comment] 2021-03-01 01:28
@leni-msft , can you have a look at this issue?

**Comment by leni-msft** [comment] 2021-03-01 05:49
@MWL88 under which situation did this issue happen? It's actually a json schema object in examples. If you're using autorest, try use the latest version.

**Comment by MWL88** [comment] 2021-03-07 15:25
@leni-msft We use the Azure REST API OpenAPI specs to drive a reporting tool that is executed periodically. The reporting tool uses NPM package `@apidevtools/swagger-parser` to parse the OpenAPI specs and it appears to attempt to resolve every reference it encounters.

I appreciate this broken reference is _only_ in an example, but the NPM package I am using does not differentiate between _example_ references which should be ignored and references that should be resolved.

Please let me know if Microsoft plans to fix this broken reference shortly.
Thanks

**Comment by leni-msft** [comment] 2021-03-08 06:37
@MWL88 I'm afraid we won't fix it. It's by design to denote a literal json schema in the examples. So with `x-ms-examples` extension, the `$ref` inside should be considered as escaped.

**Comment by leni-msft** [comment] 2021-03-08 06:46
@MWL88 let me know if more questions/doubts. I will close the issue.

**Closed by leni-msft** 2021-03-08 06:46 UTC
Labels: API Management, question
