### ISSUE TITLE
[AKS] ManagedClusterAddonProfile not picked up by docs

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-rest-api-specs#3242] opened 2018-06-14 20:32 UTC
I was surprised to find that `ManagedClusterAddonProfile` has not been properly picked up by docs: <https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/createorupdate>.

The spec [[1]] appears correct and the model has been generated correctly in the Go SDK [[2]].

[1]: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerservices/resource-manager/Microsoft.ContainerService/stable/2018-03-31/managedClusters.json#L1217
[2]: https://github.com/Azure/azure-sdk-for-go/blob/latest/services/containerservice/mgmt/2018-03-31/containerservice/models.go#L1023

cc @mboersma

**Comment by dsgouda** [comment] 2018-06-14 20:38
@kirthik Who can we tag from the documentation team here

**Comment by mmacy** [comment] 2018-06-14 21:50
@dsgouda Digging into this now, will update when we have more info.

Cc: @mboersma @kirthik @rloutlaw

**Comment by mmacy** [comment] 2018-06-18 16:53
@dsgouda Quick update on this: Initial investigation has not revealed root cause; Live Site Issue #73589353 has been filed.

Cc: @neilpeterson

**Comment by mmacy** [comment] 2018-07-10 15:53
@dsgouda Update: The addOnProfiles type is now rendered, however, it's not resolved with a link to its definition. MSEng bug 1292854 has been opened and is currently in state Active.

Cc: @iainfoulds

**Comment by dsgouda** [comment] 2018-07-30 17:34
@mmacy any updates here?

**Comment by dsgouda** [comment] 2018-07-30 18:25
Thanks for the update @mmacy .

**Closed by dsgouda** 2018-07-30 18:25 UTC
