### ISSUE TITLE
Azure RedHat OpenShift 2022-09-04 - Internal Server Error

### ISSUE THREAD

**Issue by mbfrahry** [Azure/azure-rest-api-specs#23355] opened 2023-03-29 16:09 UTC
Reopening #22514. Redhat fixed the delete issue I was having but we're still seeing Internal Server Error when anything is passed to the api incorrectly. 

When looking into RedHat OpenShift Cluster, we see Internal Server Error often with no additional details for what is happening. Right now I am sending the following to the API:
```
{
	"location": "westeurope",
	"name": "acctestaro230206170850589086",
	"properties": {
		"apiserverProfile": {
			"visibility": "Public"
		},
		"clusterProfile": {
			"domain": "fv3wp.com",
			"fipsValidatedModules": "Disabled",
			"pullSecret": "",
			"resourceGroupId": "/subscriptions/000-0000-0000/resourceGroups/aro-fv3wp.com"
		},
		"ingressProfiles": [{
			"name": "default",
			"visibility": "Public"
		}],
		"masterProfile": {
			"diskEncryptionSetId": "",
			"encryptionAtHost": "Disabled",
			"subnetId": "/subscriptions/000-000-000/resourceGroups/acctestRG-aro-230206170850589086/providers/Microsoft.Network/virtualNetworks/acctestvirtnet230206170850589086/subnets/main-subnet-230206170850589086",
			"vmSize": "Standard_D8s_v3"
		},
		"networkProfile": {
			"podCidr": "10.128.0.0/14",
			"serviceCidr": "172.30.0.0/16"
		},
		"servicePrincipalProfile": {
			"clientId": "XXXX",
			"clientSecret": "XXX"
		},
		"workerProfiles": [{
			"count": 3,
			"diskEncryptionSetId": "",
			"diskSizeGB": 128,
			"encryptionAtHost": "Disabled",
			"name": "worker",
			"subnetId": "/subscriptions/000-000-000resourceGroups/acctestRG-aro-230206170850589086/providers/Microsoft.Network/virtualNetworks/acctestvirtnet230206170850589086/subnets/worker-subnet-230206170850589086",
			"vmSize": "Standard_D4s_v3"
		}]
	},
	"tags": {}
}
```

This inevitably fails and returns

```
{
	"id": "/subscriptions/000-000-000/providers/microsoft.redhatopenshift/locations/westus/operationsstatus/0cb6d5f7-e249-4797-837c-50ddc338b6ad",
	"name": "0cb6d5f7-e249-4797-837c-50ddc338b6ad",
	"status": "Failed",
	"startTime": "2023-02-07T16:52:14.139187157Z",
	"endTime": "2023-02-07T17:02:17.699845524Z",
	"error": {
		"code": "InternalServerError",
		"message": "Internal server error."
	}
}
``` 

with no additional details on why it failed. Is there any way we can get more details added on why clusters are failing to create?

**Comment by navba-MSFT** [comment] 2023-03-31 03:16
Adding Service team to look into this.
@mjudeikis, @jim-minter, @julienstroheker, @amanohar Could you please look into this issue, once you get a chance ? Thanks in advance.

**Comment by jim-minter** [comment] 2023-04-10 15:02
@weinong please could you forward this to someone in the ARO team?  Also I'm not sure where the aliases above were configured but I think all of them are wrong now.

**Comment by weinong** [comment] 2023-04-13 18:00
@mbfrahry in general, you should open a support request, but i can help you take a look. when did you see the internal server error, though? was it during create or delete? the most recent internal server error I see was on Feb 15th during Delete

**Comment by mbfrahry** [comment] 2023-04-19 23:16
Hi @weinong, I'm seeing this issue on Create and Delete. I'm not looking for what exactly caused my issue on the 15th but more just having the api return a better error than Internal Server Error.

**Comment by weinong** [comment] 2023-04-19 23:28
Hi @mbfrahry, absolutely! We have an ongoing effort to categorize these internal server errors and expose them to users when they make sense. So I'd love to understand what error you actually hit and how we can improve that.

**Comment by mbfrahry** [comment] 2023-04-21 23:00
That's great news @weinong. So I just got another Internal Server Error today. It was during Create on April 21 at 4PM PST. Is that enough for you to find it or did you need any other information?

**Comment by weinong** [comment] 2023-04-21 23:18
@mbfrahry can you share resource ID with me at weinongw at microsoft dot com

**Comment by mbfrahry** [comment] 2023-04-21 23:23
Email sent! Thank you

**Comment by katbyte** [comment] 2023-04-25 21:05
@weinong - the root issue here is the fact these errors are not being properly bubbled up. Instead of simply returning `Internal Server Error` the actual cause of the error should also be returned/included. Having to reach out to support/service team every time one is hit is not sustainable for developing/maintaining code that depends on this API, nor for releasing a terraform resource where users could trigger an error and then open issues on the provider seeking assistance, which we will not be able to give due to the vagueness of the error message.

ie this issue is not about a specific internal error, but that the API does not include any additional details as to what caused the error.

**Comment by weinong** [comment] 2023-04-25 21:26
Hi @katbyte, I understand your pain, but at the same time there are always two kinds of errors: user actionable error and errors from the platform that won't make any sense to the end user. We are trying hard to categorize them whenever it makes sense. As I told @mbfrahry in the email, the root cause here is missing perission, but it's indeed our bug such that the error is not properly returned. We will be addressing that. 

Feel free to reach out to me via email. I'm closing this issue as I relayed the root cause to @mbfrahry already.

**Closed by weinong** 2023-04-25 21:26 UTC
Labels: question, Service Attention, customer-reported, ARO, needs-team-attention
