### ISSUE TITLE
[DataFactory] Cannot create with public Github repo

### ISSUE THREAD

**Issue by hbuckle** [Azure/azure-rest-api-specs#3643] opened 2018-08-15 12:38 UTC
If I add a public Github repo through the Data Factory GUI then query it with the API the repoConfiguration looks like this

```json
{
  "name": "acctestdfv2",
  "id": "/subscriptions/xxx/resourceGroups/acctestrg/providers/Microsoft.DataFactory/factories/acctestdfv2",
  "type": "Microsoft.DataFactory/factories",
  "properties": {
    "provisioningState": "Succeeded",
    "createTime": "2018-08-15T12:06:49.0197303Z",
    "version": "2018-06-01",
    "repoConfiguration": {
      "type": "FactoryGitHubConfiguration",
      "hostName": "",
      "accountName": "hbuckle",
      "repositoryName": "dftest",
      "collaborationBranch": "master",
      "rootFolder": "/",
      "lastCommitId": ""
    }
  },
  "eTag": "\"1a009a27-0000-0000-0000-5b741b6d0000\"",
  "location": "northeurope",
  "tags": {}
}
```

If I then attempt to create a new Data Factory using the same repoConfiguration it fails

```
PUT https://management.azure.com/subscriptions/xxx/resourceGroups/acctestrg/providers/Microsoft.DataFactory/factories/acctestdfv2?api-version=2018-06-01 HTTP/1.1
Host: management.azure.com
Content-Length: 221
Authorization: Bearer xxx
Content-Type: application/json; charset=utf-8
Accept-Encoding: gzip

{
  "location": "northeurope",
  "properties": {
    "repoConfiguration": {
      "accountName": "hbuckle",
      "collaborationBranch": "master",
      "hostName": "",
      "repositoryName": "dftest",
      "rootFolder": "/",
      "type": "FactoryGithubConfiguration"
    }
  },
  "tags": {}
}
```

Error:

```json
{
  "error": {
    "code": "InvalidPropertyValue",
    "message": "Invalid value for property 'repoConfiguration'",
    "target": null,
    "details": null
  }
}
```

**Comment by metacpp** [comment] 2018-08-16 23:09
@hbuckle without personal access token, the configuration will not work.

**Comment by hbuckle** [comment] 2018-08-17 05:59
Personal access token for GitHub? There's no option in [FactoryGitHubConfiguration](https://docs.microsoft.com/en-us/rest/api/datafactory/factories/createorupdate#factorygithubconfiguration) to pass one in

**Comment by tombuildsstuff** [comment] 2018-08-17 06:02
@metacpp also as this is a public Github repo it shouldn't need an access token?

**Comment by anuchandy** [comment] 2018-08-20 17:15
looping @hvermis as well.

**Comment by LijuanZ** [comment] 2018-08-23 22:29
@hbuckle Instead of calling factory createUpdate API with repoConfiguration to setup github repo, you need to call configureFactoryRepo API after factory creation. API doc: https://docs.microsoft.com/en-us/rest/api/datafactory/factories/configurefactoryrepo. To call this API, you'll need to have administrator permissions for the Azure subscription used by the factory.

GitHub auth is not needed to associate a GitHub repo via API.

**Comment by hbuckle** [comment] 2018-08-24 20:41
The call to configureFactoryRepo succeeds using the code below

```powershell
$token = (& az account get-access-token | ConvertFrom-Json).accessToken
$authHeader = @{
"Authorization" = "Bearer $token"
}
$PSDefaultParameterValues = @{
"Invoke-RestMethod:Headers"         = $authHeader
"Invoke-RestMethod:ContentType"     = "application/json"
"Invoke-RestMethod:UseBasicParsing" = $true
}
$body = @"
{
  "factoryResourceId": "/subscriptions/xxx/resourceGroups/dftest/providers/Microsoft.DataFactory/factories/dftestytest",
  "repoConfiguration": {
    "accountName": "hbuckle",
    "collaborationBranch": "master",
    "repositoryName": "dftest",
    "rootFolder": "/",
    "type": "FactoryGithubConfiguration"
  }
}
"@
$uri = "https://management.azure.com/subscriptions/xxx/providers/Microsoft.DataFactory/locations/northeurope/configureFactoryRepo?api-version=2018-06-01"
irm -Method Post -Uri $uri -Body $body
```

However on accessing the data factory UI I get the message `You don’t have access to the code repository. You can continue working directly with the Data Factory.`
The account I used to call the API is a subscription owner

**Comment by LijuanZ** [comment] 2018-08-24 21:01
Hi @hbuckle at lease this means you've successfully associated the factory with github repo https://github.com/hbuckle/dftest. If you call getFactory, you should be able to see repoConfiguration property in the response.
Usually, the message you got indicates the factory could not access the github repo associated. Did you get prompted to login to github when loading the factory?

**Comment by hbuckle** [comment] 2018-08-28 14:51
@LijuanZ Yes the repo configuration is present in the API response, however there was no prompt to login to github when opening the factory, just the message that the repo could not be accessed. If I go to configure git integration in the UI it starts from scratch, the settings passed in through the API are not present

**Comment by tombuildsstuff** [comment] 2018-08-28 19:16
@hbuckle out of interest does it work if you specify `https://username:password@github.com/user/repo.git` as the URI? This format should also work with Tokens (either with a username, or IIRC there's another username you can use for other tokens) which shouldn't require the connection to Github?

**Comment by LijuanZ** [comment] 2018-08-28 19:51
@hbuckle I could not reproduce the issue. I tried associate my github repo with factory via configureFactoryRepo api and then open the factory in UI portal, I got a dialog saying "Canot access GitHub. The data factory is configured to use GitHub repository: <my github repo url>. If you want to use your GitHub repository, please login." And I can use the repo after click on the "Log in to GitHub" button and follow the GitHub login flow. 

The response of getFactory is like:
{
  "name": "<my factory name>",
  "id": "<my factory resource id>",
  "type": "Microsoft.DataFactory/factories",
  "properties": {
    "provisioningState": "Succeeded",
    "createTime": "2018-07-06T19:53:51.7734269Z",
    "version": "2018-06-01",
    "repoConfiguration": {
      "type": "FactoryGitHubConfiguration",
      "accountName": "msftimteam",
      "repositoryName": "testBug2",
      "collaborationBranch": "master",
      "rootFolder": "/"
    }
  },
  "eTag": "\"010009cc-0000-0000-0000-5b85a3a80000\"",
  "location": "<my factory location>",
  "tags": {}
}

Can you try open the factory in a private/incognito window and see if it works?

If it's still not working, can you share what's the response you get from getFactory API? Also, during factory loading time in UI, can you go to developer tool and find github related API calls in the Network and share the payload? Make sure you don't share any github token here.

**Comment by hbuckle** [comment] 2018-09-05 08:17
Thanks @LijuanZ I can confirm that using `FactoryGitHubConfiguration` works. It looks like the case is [incorrect in the specs](https://github.com/Azure/azure-rest-api-specs/blob/5c2e24043ec5342c8fef7960e529cec5f12c89c2/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/datafactory.json#L3152) so downstream SDKs will also see this issue, can this be corrected?

**Comment by LijuanZ** [comment] 2018-09-05 22:11
@hbuckle Thank you for the confirmation, we are working on a fix for it.

**Comment by ajay-arora** [comment] 2018-09-25 19:33
We have checked in a fix for the UI loading issue too, which means if you have existing factories with repo configuration in a different case, the UI will now be able to load them successfully.
The fix is going to make its way to production hopefully by end of next week.

**Comment by anuchandy** [comment] 2018-11-19 05:33
@hbuckle based on Ajay's latest comment, the fix should be already deployed. Closing the issue, feel free to re-open if you still see the issue.

**Closed by anuchandy** 2018-11-19 05:33 UTC
Labels: Data Factory, Service Attention
