### ISSUE TITLE
Storage Account listKey API counts as write operation

### ISSUE THREAD

**Issue by sylr** [Azure/azure-rest-api-specs#6363] opened 2019-06-17 12:34 UTC
Hi,

We came to notice calls to `/subscriptions/<subscription>/resourceGroups/<group>/providers/Microsoft.Storage/storageAccounts/<storage>/listKeys?api-version=2018-07-01` returns a decremented `x-ms-ratelimit-remaining-subscription-writes` header leading to understand that this API is categorized as a WRITE operations where we believe it should be a READ one.

Is that a bug ?

Regards.

**Comment by MyronFanQiu** [comment] 2019-06-20 00:26
@sylr Thanks for opening this issue! I'm sorry I need some time to investigate this one. I will share any update with you here.

**Comment by MyronFanQiu** [comment] 2019-06-20 00:28
@stankovski would you please also check this issue?

**Comment by tombuildsstuff** [comment] 2019-06-20 07:26
to add some additional context from our side: this behaviour means that when a ReadOnly lock is applied to the storage account, it's not possible to read those keys

**Comment by sergey-shandar** [comment] 2019-06-27 00:33
@XiaoningLiu @JasonYang-MSFT @vinjiang - Can you please take a look at this issue?

**Comment by blueww** [comment] 2019-06-27 02:04
@huizlAzure 
Would you please help to look at the issue on server behavior Storage Account listKey API?

**Comment by sylr** [comment] 2019-07-29 13:07
Hi,

Could we have an update about this issue ?

Regards.

**Comment by musicislife08** [comment] 2019-07-29 14:44
also looking for an update as we would like to use readonly management locks with terraform and this is preventing that

**Comment by sylr** [comment] 2019-09-13 12:30
@huizlAzure @blueww @MyronFanQiu can we have a status on this ?

**Comment by MyronFanQiu** [comment] 2019-09-16 01:31
@huizlAzure Hello. Any update?

**Comment by blueww** [comment] 2019-09-18 01:35
@sylr，@musicislife08, @MyronFanQiu 
We have contact SRP and ARM team for this issue. 
They are still discussion this issue. Will update  when get result.

**Comment by zhusijia26** [comment] 2019-10-29 20:06
@blueww any update on this issue? Or could you please assign this to the right person (who is looking into it)?

**Comment by blueww** [comment] 2019-10-30 07:33
Per the latest information I get, this is from ARM. 
>>there is two level of throttling: the ARM level and the SRP level.  x-ms-ratelimit-remaining-subscription-writes comes from ARM throttling.

There's a mail to ARM team, and I just ping it for responds.

BTW, this is not a swagger bug, but a server issue.

**Comment by kartikshah9** [comment] 2019-12-19 18:17
@blueww request an update on this. If we need to consider re-assigning to a different team please initiate the thread and re-assign

**Comment by zhusijia26** [comment] 2020-01-09 07:25
@blueww please provide an update on this issue.

**Comment by blueww** [comment] 2020-01-09 07:35
@zhusijia26 
I have ping ARM team again for this.
Will update this issue when get any update from them.

**Comment by blueww** [comment] 2020-02-05 12:23
@zhusijia26
Following is the message I get from SRP/ARM team. 
In a word, this is by design for security. 

> ListKeys retrieves secrets of the Storage Account therefore, it is modeled as a Write action by design for your account’s security, as Write operation requires higher privileged RBAC permissions. That said, we have taken actions to raise throttling limit for ListKeys to a much higher value. Please let us know if this resolves your issues.

**Comment by blueww** [comment] 2020-02-05 12:24
@zhusijia26
As this is by design, I will close this issue.
Feel free to contact us if you need further assistance.

**Closed by blueww** 2020-02-05 12:24 UTC
Labels: Bug, Service Attention, Storage

**Comment by tombuildsstuff** [comment] 2020-02-05 13:36
@blueww sorry to push here - but the [original issue](https://github.com/Azure/azure-rest-api-specs/issues/6363#issue-456910046) here is that this design is not what users expect - presumably this should be a Read operation with a separate permission to retrieve this, rather than a Write operation? As it stands there's no means of retrieving the Storage Account Key via the API when there's a Write Lock on the storage account, since this counts as a Write operation?

As such could we re-open this issue and confirm with the ARM team if they plan to fix this?

Thanks!

**Comment by blueww** [comment] 2020-02-06 04:06
@tombuildsstuff 
When you get the storage account key, you can do write operation on storage objects (like container,blob ...). So for security reason, user with only read access, can't list storage account key.

Actually, we have discussed this with ARM team, and currently there's no plan to change this.

**Comment by tombuildsstuff** [comment] 2020-02-06 06:46
@blueww there’s a difference between Data Plane and Resource Manager operations. When there’s a write lock on the storage account this only affects Resource Manager operations - and not the Data Plane API.

However if you’re unable to get the Storage Account Key from the Resource Manager API due to the Write Lock you’ll be unable to upload content via the Data Plane API. An error is returned from the Storage Resource Manager API’s when trying to list the keys once a Write lock has been added to the storage account regardless of the users permissions.

It’s worth noting there’s entirely valid use-cases for a user/service principal having read-only access to the Resource Manager API to obtain one of the Primary/Secondary Storage Account Keys to be able to access the Data Plane API’s. Unfortunately this is required due to the flawed rollout of AzureAD authentication for the Storage API’s - where the new storage roles haven’t been backported to existing contributor/owner role assignments and instead only apply to new role assignments.

This ultimately means that we’ve had many users spend large amounts of time debugging AzureAD permissions with two users in the same role - and still be unclear about why these accounts have different permissions. Unfortunately this means that AzureAD authentication isn’t usable as the primary authentication mechanism for the Storage API’s at this time.

As such - can we please get this issue reopened and re-reach out to the ARM team here?

Thanks!
