### ISSUE TITLE
compute (2019-12-01): Is HardwareProfile.vmSize out of date?

### ISSUE THREAD

**Issue by wata727** [Azure/azure-rest-api-specs#10033] opened 2020-07-04 13:50 UTC
Hi team,

I'm the author of a [lint tool](https://github.com/terraform-linters/tflint-ruleset-azurerm) for Terraform using this API specification. For example, the correct value for vmSize of a virtual machine is checked against the following enum definition:
https://github.com/Azure/azure-rest-api-specs/blob/c57ad5f5b7f30d8da1a7aae9f7801e4714f3d155/specification/compute/resource-manager/Microsoft.Compute/stable/2019-12-01/compute.json#L7316-L7481

However, I have received reports that I am getting an error for the correct vmSize because `Standard_D2ds_v4` is not included in this list. Is this list out of date? Please tell me if there is something wrong with where I should refer.

Thanks in advance.

**Comment by Drewm3** [comment] 2020-07-10 06:22
It does look like the enum in the spec is out of date. Let me check to see why the spec is not getting updated with new sizes.

**Comment by Drewm3** [comment] 2020-07-13 17:51
Hi @wata727, I have checked with the compute resource provider API team, and they have informed me that this enum list is no longer updated. This is because the sizes available change in some cases on a per-subscription basis such as when we release limited preview sizes that are only available to customers who have opted into the preview program. Therefore we highly recommend that you leverage the [VM SKUs API](https://docs.microsoft.com/en-us/rest/api/compute/resourceskus/list) to get an accurate list of the sizes available for a selected subscription.

We are discussing internally how to update the API spec you mentioned to clarify that the enum list does not contain all VM sizes available. It is likely that we will either remove the enum list completely or reduce it to a single size in the future to eliminate this possible confusion that is caused by a list that contains only about 50% of the currently available sizes.

**Comment by wata727** [comment] 2020-07-15 16:59
Hi @Drewm3, thank you for your reply.

Is it possible to include all available sizes in the list, including preview sizes? I understand that some subscriptions may include sizes that aren't really available, but for our use case, that's enough.

If this is possible, I would appreciate your consideration. Thanks.

**Comment by Drewm3** [comment] 2020-07-29 23:00
Unfortunately, our new behavior for VM sizes will not support the ability of maintaining this list. So, my guidance is to remove the majority of these sizes from the list so that folks will not be confused by the partially complete list of sizes. 

@bilaakpan-ms, let's work together to get this list of sizes reduced in the spec to avoid future confusion.

**Comment by Drewm3** [comment] 2020-10-15 18:19
The team has decided that we will be removing the list of VM sizes from the Swagger spec with the next API version update. Consumers of the API spec should stop relying on this list of VM sizes now if possible, and it will be formally removed in the upcoming API update.

**Comment by amjads1** [comment] 2020-11-17 02:04
I see that Bila was assigned to this issue but somehow it got auto unassigned. I'm going to assign it back to Bila and update him as well.

**Comment by amjads1** [comment] 2020-12-23 18:42
@bilaakpan-ms Can you please share latest updates here?

**Comment by Drewm3** [comment] 2021-03-25 18:06
To provide an update on this issue: Microsoft is not going to be able to maintain this list in the swagger files, and instead customers must use the Azure VM SKUs API to query what sizes are currently available. We intend to remove this list of SKUs in the swagger file to provide clarity that it is not a maintained list, but that action is delayed internally because a change like this is being considered a "breaking change" that requires an exception or 3 year notification. So at this time the list of sizes is frozen with new sizes not being added and existing sizes remaining in the list.

**Comment by Drewm3** [comment] 2021-06-21 05:29
Closing this item because it is now "by design" that this list is frozen and will become further and further out of date until the list is formally removed at the end of Dec. 2023.

**Closed by Drewm3** 2021-06-21 05:29 UTC
Labels: Compute, Compute - VM, Service Attention, bug, customer-reported
