### ISSUE TITLE
Service responses don't always contain 'required' properties indicated in their schema definition

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-rest-api-specs#790] opened 2016-12-09 01:53 UTC
When running swagger validation tools on the existing specs, one class of error found is that responses from service are missing required properties. Examples: https://github.com/Azure/azure-rest-api-specs/issues/755, https://github.com/Azure/azure-rest-api-specs/issues/772

The cause of this issue is models shared for request and response, with required properties for the request, but those not coming back in the response. 

SDKs generated from AutoRest are generally not exposing this as a problem, because they are not validating responses against models. The consumer obtains the response even if it doesn't match the expected model. It's up to the consumer to use the response properly afterwards.

Answers to the following questions can help choose an solution for an accurate swagger representation:
	1. Are properties marked as required really required?
	2. Is GET->PUT pipeline scenario expected to work for the consumer of the SDK?

If the service does not send the 'required' properties in the response, then piping scenario would be broken even if the models (or model types) are the same, as sending the response of a 'GET' in a 'PUT' request, would result in an error indicating that's missing required properties. 

A common case for these 'required' properties are passwords/access keys, which are required in the request but won't be returned to the user in the response. In this case, the user would need to provide the password/access key for the PUT call to work

Options to resolve the above in the swagger spec:

A. If the properties are accurately required for the request, but not expected to come back in the response (the GET->PUT piping scenario is not expected to work as is), then the model definition for the result could be broken up into 2 models: model 'A' would contain the shared properties, and model 'B' being an "allOf" of A. This way model 'B' expands on model 'A' with the additional required properties.
	Generated code would represent these as different models, so the consumer of the SDK would 'GET' model A, and need to construct model B with the additional properties for a 'PUT'. 
     
B. If the properties are not required under certain circumstances (depending on other properties for example) then the model for request and response would be the same and those properties should not be indicated as required in the spec.

@amarzavery , @johanste, does this properly capture what we discussed yesterday? Feel free to comment. 
@lmazuel , @begoldsm, we'd really appreciate your feedback on this.
@salameer

**Comment by begoldsm** [comment] 2016-12-09 19:11
@veronicagg thank you so much for putting this summary together. From our side, I think A will work for the vast majority of cases. There is one other scenario where we "re-use" objects with required properties, and that is in LIST calls (get all the resources in a resource group or subscription). In this case, by design, the properties of those resources are omitted by the service to reduce the payload size. 
We would not want to require another different object in this case that the user needs to know about/manage, but perhaps this would still fit under option A?

For example: An 'account' object in a PUT requires location, properties.varA, properties.VarB, properties.Password.
A specific GET for that account returns an object with everything **except** properties.Password
A GET on the resource group containing the account only returns the top level object (name, location, in this case).

Would this mean that we need three difference object model definitions:
1. baseAccount (contains all common properties, no required ones)
2. specificGetAccount (allOf baseAccount + properties.varA, properties.VarB)
3. putAccount (allOf specificGetAccount + properties.Password)

This seems a bit heavy handed, but it is the most explicit modelling. That being said, I am open to suggestions, but bear in mind that any of these changes will result in a breaking change for all existing SDKs and specs.

**Comment by veronicagg** [comment] 2016-12-12 23:01
@begoldsm Thanks for the feedback! What you describe looks to me like the most comprehensive approach for that case, I agree that's a little heavy, but reflects the API. 
I understand that this type of change would result in breaking changes, and we may choose not to do them immediately if it's not the right time, we can discuss when to do those separately and align them with other changes. 
It'd be great to hear what others think.

**Comment by Nilambari** [comment] 2017-08-17 19:52
As specified in swagger, properties do get populated in case of GET for VirtualNetworkGateway/LocalNetworkGateway objects.
In case of GET of Connection object, its referened (VirtualNetworkGateway/LocalNetworkGateway) obeject's properies are not fully populated, it was as per design and changing this would be a breaking change and we will think of doing it in future but right now it is as per the design.
This is not a blocking issue as we do not use referenced objects for calling SET. Still, we can do SET on connection object with this returned connection object in response of GET connection.

Please let us know if you have further queries. Help up close this issue.

**Comment by veronicagg** [comment] 2017-08-23 19:16
We may look into addressing this at model validation level first to reduce noise: https://github.com/Azure/oav/issues/156

**Comment by salameer** [comment] 2018-10-09 00:43
Hi Veronica and @sergey-shandar what's the status here?

**Comment by akning-ms** [comment] 2021-05-14 07:46
It can be detected in our Live validation service now. so close it

**Closed by akning-ms** 2021-05-14 07:46 UTC
Labels: Tooling Team, discussion, feature-request, internal-ms
