### ISSUE TITLE
[Redis] x-ms-client-flattening is used incorrectly

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-rest-api-specs#732] opened 2016-11-16 19:15 UTC
Regarding issue https://github.com/Azure/azure-sdk-for-go/issues/459 found by @tombuildsstuff 

cc:
@TimLovellSmith

**Comment by tombuildsstuff** [comment] 2016-11-17 06:06
Thanks @vishrutshah

**Comment by mcardosos** [comment] 2016-11-18 01:32
cc @amarzavery @SiddharthChatrolaMs @hovsepm
Looking at the issue in more detail...
This issue was found on the [Go SDK](https://github.com/Azure/azure-sdk-for-go/issues/459), and it looks like it has to do do with `x-ms-client-flatten`. Currently the Go generator does not support the flattening extension.
In the other hand, take a look into the extension [doc](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-extensions.md#x-ms-client-flatten). Flattening is used just to make the code look better and less cumbersome. Completely optional. If the extension is ignored, the generated code still works.
The problem here is that `x-ms-client-flattening` is used [incorrectly](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-redis/2016-04-01/swagger/redis.json#L856) in the redis swagger. Whatever is inside `RedisCreateProperties` (it happens to be `sku`) should not be flattened. As the wire looks like this...
```
{
	"id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/acctestRG-8068841053713972281/providers/Microsoft.Cache/Redis/acctestRedis-8068841053713972281",
	"location": "West US",
	"name": "acctestRedis-8068841053713972281",
	"type": "Microsoft.Cache/Redis",
	"tags": {},
	"properties": {
		"provisioningState": "Succeeded",
		"redisVersion": "3.0",
		"sku": {
			"name": "Basic",
			"family": "C",
			"capacity": 1
		},
		"enableNonSslPort": false,
		"redisConfiguration": {
			"maxclients": "1000",
			"maxmemory-reserved": "50",
			"maxmemory-delta": "50"
		},
		"accessKeys": null,
		"hostName": "acctestRedis-8068841053713972281.redis.cache.windows.net",
		"port": 6379,
		"sslPort": 6380
	}
}
```
`sku` should be included in `RedisResourceProperties`, along with `RedisVersion`, `ProvisioningState`, etc.
Flattening has nothing to do with the wire. The redis swagger should be fixed so `x-ms-client-flattening` is only used in the correct places; and the models are faithfully describing the API.

**Comment by TimLovellSmith** [comment] 2016-11-18 17:14
@mcardosos That also implies a bug with the flattening is implemented for the other languages e.g. C# then.

**Comment by mcardosos** [comment] 2016-11-18 19:02
Right now this wrong swagger generates working code because of an AutoRest bug. @amarzavery is the one who debugged this and can explain it better.

**Comment by amarzavery** [comment] 2016-11-18 19:31
I would like to explain few things, based on my findings
- `json object is like a case sensitive dictionary`. Swagger spec has the property name modeled as `"RedisConfiguration"` **(PascalCase)** whereas the payload example says it is `"redisConfiguration"` **(camelCase).** The swagger spec should accurately represent what is there on the wire. This will result in [de]serialization issues. We have seen this issue many times when the service implements their server code in C# and the CSharpiness oozes out in the swagger spec. The general convention says that all the properties of the json object should be camelCase.
- `"x-ms-client-flatten": true` is a _lipstick applied in the generated_ code to provide better user experience to the customer (so that he does not have to do `Foo.properties.provisioningState` and can **easily access the model property** as `Foo.provisoningState` . This has no bearing on the wire format. 

In the Redis spec, the flattening extension is applied incorrectly to achieve what you want in the generated code. (I agree that it is a bug in AutoRest  w.r.t client flattening (the way in which it allowed you to get what you want. The serialization format/ JSON annotation in C#.net library should have been `[properties.properties.RedisConfiguration]` whereas what got generated is `[properties.**r**edisConfiguration]`. Look at the  generated `C#.net client code` over **[here](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/RedisCache/Microsoft.Azure.Management.Redis/Generated/Models/RedisResource.cs#L105)**. _"Flattening" (wire format json annotation) and the "casing" both are incorrect_. 

> On a lighter note:  Looks like the Redis team got some kind of a spyware induced inside AutoRest to achieve what they want ;).

To give you some visualization of the incorrect modeling in the swagger spec, this is how the class diagram looks like based on the modeling in the swagger spec. Notice two levels of `properties.properties` (an anti-pattern). This is not what the wire format is.

![image](https://cloud.githubusercontent.com/assets/4521223/20443398/7f0e7522-ad81-11e6-9b6d-11843342e67b.png)

We are investigating the root cause of the problem (what made AutoRest generate the desired code from an incorrectly modeled swagger spec).

/cc @hovsepm, @fearthecowboy, @johanste, @markcowl

**Comment by TimLovellSmith** [comment] 2016-11-21 22:50
@amarzavery Hm. What is x-ms-external supposed to do?

**Comment by amarzavery** [comment] 2016-11-21 23:16
Whenever a model definition is marked as ["x-ms-external](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-extensions.md#x-ms-external), it is an indication to AutoRest "To not generate a model class for this model. Do not fail during code generation wherever this model is referenced. The spec Author will provide this class **manually** in the same namespace."

**Closed** 2016-11-23 19:25 UTC
