### ISSUE TITLE
Swagger spec doesn't account for paging.

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-rest-api-specs#81] opened 2015-12-01 18:22 UTC
In the swagger spec, for networking for example, there is an implication that the List api returns all results, rather than just the first page.

> List the List network security rule operation retrieves all the routes in a route table.

But it doesn't retrieve all the routes. It returns the first page and then one can use ListNextResults to get the subsequent page(s). Also, the generated sentence doesn't really parse in English correctly.

The confusion worsens when one sees the ListAll and reads the description:

> ListAll the list NetworkSecurityGroups returns all network security groups in a subscription

But it also doesn't "return all", but rather the first page and then one is expected to use ListAllNextResults to page through the results.

Go-autorest uses the swagger description to form documentation for the Go sdk. This documentation can be a bit misleading due to these descriptions.

**Comment by amarzavery** [comment] 2016-02-11 22:03
@DeepakRajendranMsft - Can you please update the documentation to be in sync with the behavior of the method.

**Comment by salameer** [comment] 2017-01-06 00:22
@DeepakRajendranMsft can you please provide some updates here?

**Comment by markjbrown** [comment] 2017-06-26 21:11
@amarzavery and @salameer, It makes no sense to update every instance of List or ListAll in Network. Shouldn't this be documented into overall API docs? Lots of services use List or ListAll and this behavior happens in many places. @liumichelle

**Comment by salameer** [comment] 2017-06-28 23:06
Hi @markjbrown,

The Overall microsoft or Azure APIs documentation would definitely make sense if the name of the operations actually described the behavior. the problem is that the use of the naming "List" & "List all" and the behavior of these operations is not consistent so even if we document that at an a higher level it will still be miss leading to the customers. 

To sum up, what's being asked here is that the documentation of the method regardless of the name actually describes the behavior of the operation

**Comment by markjbrown** [comment] 2017-06-28 23:58
I see this pattern across RP's so this isn't unique to Networking. Is this something that is standardized across other RP's as well?

**Comment by salameer** [comment] 2017-06-29 17:30
To be honest these are generic API and programming good practices and they provide customer pain. regarding other APIs we are pointing out similar issues to the Documentation team and the north star is for continuous improvement whether captured in issues or direct feedback. 

I think this effort is low hanging fruit if the fact that it doesn't cause breaking changes and greatly improves the documentation on docs.microsoft.com and the generated SDKs usage experience

Let's Make it AWESOME mark LOL :)

**Comment by salameer** [comment] 2017-06-29 17:50
Alright you know what i think I'll negate myself here. I think the issue here is that both names have the same behavior but follow two different naming conventions. Sooo fixing these will introduce breaking changes and not sure about the benefit VS impact here specially for Networking API.

Sooo Mark and @DeepakRajendranMsft  my recommendation is to follow the naming guidlines in the swagger checklist for future new APIs or resource types to have standardized naming.

 and @colemickens I think to ease your problem, Go SDK should handle lazy  enumeration or loading regardless of the name and avoid the need to use ListAllNextResults. @marstr and @mcardosos let's follow up on this.

Closing this one for now. please reopen if anyone doesn't agree

**Closed by salameer** 2017-06-29 17:50 UTC
Labels: Networking, P2

**Comment by marstr** [comment] 2017-06-29 20:41
Howdy @salameer,

As we discussed offline. We updated our support for the Pageable extension to grab each page lazily as it is requested. This should dramatically reduce the complexity involved with Listing, and should wipe away the concern about this particular type of misleading documentation.

**Comment by salameer** [comment] 2017-06-29 21:16
Awesome!

LONG LIVE @marstr
