### ISSUE TITLE
Invoke-AzCostManagementQuery not able to retrieve supported column for supported subsciption type

### ISSUE THREAD

**Issue by erroltuparker** [Azure/azure-rest-api-specs#22692] opened 2023-02-17 05:10 UTC
One of our subscriptions that we are pulling billing information for is currently returning:

```
Body:
{
  "error": {
    "code": "BadRequest",
    "message": "Invalid query definition: Invalid dataset grouping: 'ConsumedService'; valid values: 'ResourceGroup','ResourceGroupName','Resourc
eType','ResourceId','ResourceLocation','SubscriptionId','SubscriptionName','MeterCategory','MeterSubcategory','Meter','ServiceFamily','UnitOfMeas
ure','PartNumber','BillingAccountName','BillingProfileId','BillingProfileName','InvoiceSection','InvoiceSectionId','InvoiceSectionName','Product'
,'ResourceGuid','ChargeType','ServiceName','ProductOrderId','ProductOrderName','PublisherType','ReservationId','ReservationName','Frequency','Inv
oiceId','PricingModel','CostAllocationRuleName','MarkupRuleName','BillingMonth','Provider','BenefitId','BenefitName','CustomerTenantId','Customer
TenantDomainName','ResellerMPNId','PartnerEarnedCreditApplied','CustomerName','PartnerName',''.\r\n\r\n"
  }
}
```

but based on https://learn.microsoft.com/en-us/azure/cost-management-billing/understand/understand-usage this is a supported column for all subsciption types.

This column works for our other subscriptions. The subscription type that we are getting this error on is called "Azure Plan".

**Comment by navba-MSFT** [comment] 2023-02-21 03:10
@erroltuparker Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment] 2023-02-21 06:04
Closing this issue as duplicate of https://github.com/Azure/azure-powershell/issues/20953

**Closed by navba-MSFT** 2023-02-21 06:04 UTC
Labels: question, customer-reported, CXP Attention
