### ISSUE TITLE
Change In API behavior?

### ISSUE THREAD

**Issue by dbilleci-lightstream** [Azure/azure-rest-api-specs#7207] opened 2019-09-12 23:38 UTC
I'm using PULUMI which is based on Terraform providers for azure.  I've checked their bugs page and don't see anything related.

I'm running into an issue where if I create a simple VM which gets linked to an existing load balancer, and then try to destroy it, I get a new error message which I believe is from the API:

Created resources:
````
azure:core:ResourceGroup
azure:network:NetworkInterface
azure:network:NetworkInterfaceBackendAddressPoolAssociation
azure:compute:VirtualMachine
````

Then, on teardown of resources, I get this failure:
````
  pulumi:pulumi:Stack (compute-api-compute-api-b-stage-eus2):
    error: update failed

  azure:network:NetworkInterfaceBackendAddressPoolAssociation (api-B-P-0-Stage-Eus2-Assoc):
    error: Plan apply failed: deleting urn:pulumi:compute-api-b-stage-eus2::compute-api::azure:network/networkInterfaceBackendAddressPoolAssociation:NetworkInterfaceBackendAddressPoolAssociation::api-B-P-0-Stage-Eus2-Assoc: Error waiting for removal of Backend Address Pool Association for NIC "api-B-Vm-0-Stage-Eus2-Nic" (Resource Group "api-B-Stage-Eus2-Rg"): Code="OperationNotAllowed" Message="Operation 'startTenantUpdate' is not allowed on VM 'api-B-0-Stage-Eus2-Vm' since the VM is marked for deletion. You can only retry the Delete operation (or wait for an ongoing one to complete)." Details=[]
````

I've not changed my infra code, and I got this on 2 different provider versions, one from about 2 months ago (that has been working) and now on the newest provider version today, same error.

Any ideas?

**Comment by mybayern1974** [comment] 2019-09-18 11:50
@dbilleci-lightstream , @ArcturusZhang can help take a look at the two terraform issues: [2491 ](https://github.com/terraform-providers/terraform-provider-azurerm/issues/2491)and [4330](https://github.com/terraform-providers/terraform-provider-azurerm/issues/4330) which are motivated by the issue filed at [pulumi issue 365](https://github.com/pulumi/pulumi-azure/issues/365). I cannot tell right now whether it's rest api related before investigating the terraform behavior, so i suggest close the issue here, instead, use the terraform issue to track. We can reopen this issue once we find the root cause is at here. Do you agree with this? If yes we may close this issue here in 3 days.

**Comment by dbilleci-lightstream** [comment] 2019-09-18 15:03
Sure that's fine.

**Comment by mybayern1974** [comment] 2019-09-19 02:42
Close per the author agrees. I would reopen this once finding the root cause is at rest api here.

**Closed by mybayern1974** 2019-09-19 02:42 UTC
Labels: triage
