### ISSUE TITLE
`Resources_ListByResourceGroup` returned result not up-to-date

### ISSUE THREAD

**Issue by ziyeqf** [Azure/azure-rest-api-specs#21221] opened 2022-10-21 08:26 UTC
When deleted a resource in resource group (the delete CALL returned with success), and then call the [`Resources_ListByResourceGroup`](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/Microsoft.Resources/stable/2020-06-01/resources.json#L2301), the API sometimes returns an outdated result. (The deleted resource still shows).

**Comment by RakeshMohanMSFT** [comment] 2022-11-21 03:48
@ziyeqf There is a known caching issue, we are actively working on a fix. But we do not have any ETA as of now for the same.

can you use the azure resource graph and query?

**Comment by ziyeqf** [comment] 2022-11-22 09:06
@RakeshMohanMSFT Thanks for you explain! 
We plan to check whether resources really exist or only exist in API cache by calling GET on resources returned by `Resources_ListByResourceGroup`. Will it work as we expect?

**Comment by RakeshMohanMSFT** [comment] 2022-11-22 09:14
@ziyeqf Yes, it can work but again you should consider that the result can vary depending on the region to which the call was internally made. if the replication happened on particular region you will get the result otherwise not. Therefore Resource Graph would be a better option.

**Comment by RakeshMohanMSFT** [comment] 2022-11-22 09:54
@ziyeqf I will close the issue now, if you need further assistance please reopen the issue.

**Closed by RakeshMohanMSFT** 2022-11-22 09:54 UTC
Labels: question, ARM, customer-reported, needs-author-feedback, CXP Attention, resource-manager

**Comment by tombuildsstuff** [comment] 2022-11-22 10:57
@RakeshMohanMSFT since this issue is tracking the API issue, could we keep this issue open until the API is fixed?

**Comment by RakeshMohanMSFT** [comment] 2022-11-22 11:05
@ziyeqf We already have a lot of issues for this and we have an internal thread as well for the same. Once the fix is in place, we will update all related thread.

**Comment by tombuildsstuff** [comment] 2022-11-22 11:39
@RakeshMohanMSFT can you point to another public issue tracking this that we can point customers towards?

**Comment by RakeshMohanMSFT** [comment] 2022-12-01 12:12
@tombuildsstuff Apologies! I missed your earlier ping. No, there is no public issue tracking available for this issue. Since the issue is with the Service and not with the client. You can open a support ticket with Azure Resource Manager team and get an official email from them for the same.
