### ISSUE TITLE
getting error code "MissingApiVersionParameter" for every request even pass api-version parameter

### ISSUE THREAD

**Issue by mdusman** [Azure/azure-rest-api-specs#3978] opened 2018-09-21 04:11 UTC
getting error code "MissingApiVersionParameter" for every request even I have pass api-version parameter
api-version=2017-12-01 or api-version=2018-07-12
url format:
https://management.azure.com/subscriptions/{subId}/resourceGroups/{RG}/providers/Microsoft.BotService/botServices/{botId}/channels/DirectLineChannel?api-version=2017-12-01

**Comment by marstr** [comment] 2018-09-21 19:29
Your URL formatting looks correct, and I've verified that `2017-12-01` is a [valid API Version for BotServices](https://github.com/Azure/azure-rest-api-specs/tree/acaf947b0c6140bcb22d3e56a4c87d68c18e475f/specification/botservice/resource-manager/Microsoft.BotService/preview/2017-12-01). 

Out of curiosity, to make sure that triaging to the Cognitive Services team was correct, can you tell me how you are targeting this service? Are you using one of the official SDKs, curling the endpoint directly, or maybe something else completely different?

**Comment by mdusman** [comment] 2018-09-25 10:11
I have tried this api through postman where it is throwing error. I have also tried through azure cli where it is working fine.

**Comment by marstr** [comment] 2018-11-12 18:41
Now that it is confirmed that this needs service attention, I'm removing my assignment.

**Comment by jameslew** [comment] 2019-08-30 00:05
Hi @mdusman - checked with engineering and he didn't see a reason this was happening.  He made two suggestions:

Try to get the botresource object and see if that works.

https://management.azure.com/subscriptions/{subId}/resourceGroups/{RG}/providers/Microsoft.BotService/botServices/{botId}?api-version=2017-12-01

Also, try using armclient - 

https://github.com/projectkudu/ARMClient, and see if this repros

**Comment by jameslew** [comment] 2019-10-01 15:38
Looks like this is no longer relevant given the age of the issue.  If you do have any further questions or the problem is still open, do reactivate.  Thank you!

**Comment by ChrisHMSFT** [comment] 2019-10-01 15:41
Closing the ticket per the above discussion. Please re-open if the issue still remains. 

Thanks,
Chris

**Closed by ChrisHMSFT** 2019-10-01 15:41 UTC
Labels: Service Attention

**Comment by Sankaranis** [comment] 2019-10-16 09:04
Hi @ChrisHMSFT , Getting same error while login Azure AD OAuth, I've given the Tennant_id, client_id, clientSecret.

**Comment by ChrisHMSFT** [comment] 2019-10-16 12:51
Hi @Sankaranis,

Could you please share more detail on the endpoint you are calling? Is it the same one as above?

Thanks!
Chris

**Comment by Sankaranis** [comment] 2019-10-16 13:22
Yes, it is same one. 

Endpoint - https://orgbf224511.api.crm.dynamics.com/api/data/v9.1/.
I tried to communicate the powerapps cds with azure ad auth token, which is given by flutter.
Please refer this link for azure ad auth- https://pub.dev/packages/aad_oauth#-readme-tab-

**Comment by ChrisHMSFT** [comment] 2019-10-22 01:17
Hi @Sankaranis ,

This endpoint is for Dynamics and not the bot services. Could you please open a new issue for the problem you are experiencing?

Thanks,
Chris
