### ISSUE TITLE
[Monitor] AlertRuleOperation.get does not return "operator"

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-rest-api-specs#1211] opened 2017-05-09 23:56 UTC
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-monitor/2016-03-01/swagger/alertRules_API.json#L496

According to the Swagger, the GET operation should return the AlertRuleResource object and its properties. However, when I have a rule with a Metric data source and threshold rule condition, the "operator" is not returned in the GET response.

If I look at the rule in the Portal I can see that the operator was accepted correctly, but I cannot access it through the REST API.

**Comment by olydis** [comment] 2017-05-10 17:52
Thanks @tjprescott!

@gucalder Please take a look at the above. Feel free to reassign to whoever knows best about this, I just saw that you changed given Swagger lately. 🙂

**Comment by tjprescott** [comment] 2017-05-10 17:57
Also, because of this, you cannot GET an alert object and then PUT it back because (at least in Python) you'll get an error that "Parameter 'ThresholdRuleCondition.operator' can not be None."

**Comment by gucalder** [comment] 2017-05-10 19:07
Since this is a problem detected in Python it would be good that @lmazuel, who wrote the Python SDK and commands, also investigates this. 
The spec states that threshold and operator are required in ThresholdRuleCondition, so they should be in the response and it must be GreaterThan, GreaterThanOrEqual, LessThan, or LessThanOrEqual.
I am checking the .Net SDK and the response from our servers as part of my investigation.

**Comment by tjprescott** [comment] 2017-05-10 19:11
I verified with a Fiddler trace that the server was indeed not returning this field, which is why the Python SDK deserializes it into null.

**Comment by gucalder** [comment] 2017-05-10 19:22
Yeap, I just checked that. It looks like a bug in the backend. 
I'll let our dev know about this.
Thanks.

**Comment by olydis** [comment] 2017-05-16 00:28
@gucalder Thanks for verifying! Please let us know when there is any update on this.

**Comment by tjprescott** [comment] 2017-05-17 16:21
@gucalder I've observed that this only returns `null` when the operator is GreaterThan.  For the other cases, the value is returned.

**Comment by gucalder** [comment] 2017-05-17 21:29
This is a backend issue: when the object is serialized, if operator is the default it is not serialized. That's why GreaterThan fails and all the others work.
We are fixing the issue.

**Comment by gucalder** [comment] 2017-05-17 21:36
Fixing this requires no change in the spec btw.

**Comment by tjprescott** [comment] 2017-05-17 21:46
> Fixing this requires no change in the spec btw.

I realize that, but there's nowhere else to place issues for the service team :)

**Comment by olydis** [comment] 2017-06-07 18:28
@gucalder any update on the issue? otherwise, is there an issue on your side that we can track here and close?

**Comment by olydis** [comment] 2017-09-19 19:52
@gucalder PING

**Comment by gucalder** [comment] 2017-10-10 18:51
The devs told me a long time ago that they were going to fix this. Let me ask if it is already fixed in the back-end.

BTW: the "offending" file is was moved with the last reorg of the specs. It is not here: azure-rest-api-specs\specification\monitor\resource-manager\microsoft.insights\2016-03-01

**Comment by gucalder** [comment] 2017-10-10 20:09
I can confirm that the issue has been fixed in the backend for some weeks now.
The API version remained the same since this was a bug only.

**Comment by olydis** [comment] 2018-02-21 00:35
thanks @gucalder!

**Closed by olydis** 2018-02-21 00:35 UTC
Labels: Monitor
