### ISSUE TITLE
[Virtual Machine] Segments of Some ID Properties Become Upper-Case in Response

### ISSUE THREAD

**Issue by myc2h6o** [Azure/azure-rest-api-specs#19424] opened 2022-06-13 09:25 UTC
Hi, I'm adding the support for Capacity Reservation for Virtual Machine in Terraform. While working on that, I found the CapacityReservation ID returned from service always has its Resource Group name set to upper-case. Below are the REST API request details: In the PUT request, the capacityReservationGroup id is ".../resourceGroups/**yicma**/...", but in GET response it is ".../resourceGroups/**YICMA**/..."
```
// Create the VM
PUT https://management.azure.com/subscriptions/***/resourceGroups/yicma/providers/Microsoft.Compute/virtualMachines/yicma-vm?api-version=2021-11-01
{
  "properties": {
    "capacityReservation": {
      "capacityReservationGroup": {
        "id": "/subscriptions/***/resourceGroups/yicma/providers/Microsoft.Compute/capacityReservationGroups/yicma-cap"
      }
    },
    ...
  },
  ...
}

// Get properties
GET https://management.azure.com/subscriptions/***/resourceGroups/yicma/providers/Microsoft.Compute/virtualMachines/yicma-vm?api-version=2021-11-01
{
  "properties": {
    "capacityReservation": {
      "capacityReservationGroup": {
        "id": "/subscriptions/***/resourceGroups/YICMA/providers/Microsoft.Compute/capacityReservationGroups/yicma-cap"
      }
    },
    ...
  },
  ...
}
```

Swagger link: https://github.com/Azure/azure-rest-api-specs/blob/c6b48ac6b32da8f18d9228a1f565880b02c5191d/specification/compute/resource-manager/Microsoft.Compute/stable/2021-11-01/compute.json#L13863

**Comment by myc2h6o** [comment] 2022-06-13 09:26
Same thing happens for id in `Host` and `HostGroup`
https://github.com/Azure/azure-rest-api-specs/blob/c6b48ac6b32da8f18d9228a1f565880b02c5191d/specification/compute/resource-manager/Microsoft.Compute/stable/2021-11-01/compute.json#L13819-L13826

**Comment by myc2h6o** [comment] 2022-06-14 05:54
There is a similar issue in VMSS #10016 but closed as Azure resources are case-insensitive. But according to the violation reference [roundtrip_inconsistent_property](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/Semantic-and-Model-Violations-Reference.md#roundtrip_inconsistent_property) The property in GET response should match the value in the preceding PUT request.

**Comment by jaylabell** [comment] 2022-06-30 20:34
@Drewm3 can you please take a look at this issue?

**Comment by Drewm3** [comment] 2022-08-02 05:59
This is by design within microsoft.compute. According to the architect this response is valid within the ARM spec. However, I will investigate to see if this can be modified as a feature request even though it is not technically a bug.

**Comment by Drewm3** [comment] 2022-11-04 03:51
Closing this issue. According to the compute resource provider dev teams changing this issue is an very large effort that is not something that we are able to take on any time soon since the current behavior is technically correct.

**Closed by Drewm3** 2022-11-04 03:51 UTC
Labels: Compute - VM, Service Attention, feature-request
