### ISSUE TITLE
Virtual Machine Scale Set CreateOrUpdate Fails - "The Value of Parameter zoneBalance is Invalid"

### ISSUE THREAD

**Issue by pbstrein** [Azure/azure-rest-api-specs#11805] opened 2020-11-24 20:30 UTC
## Error
When working with ARM, I get the following failure message.

"The value of parameter zoneBalance is invalid. (Code: InvalidParameter)."

From[ this Github issue ](https://github.com/Azure/azure-powershell/issues/6012), a similar error occurred in Powershell due to the PUT operation on Virtual Machine scale sets. "Any value is invalid for zoneBalance if one or zero zones are specified."

## How to Replicate
Create an ARM Deployment in a region where there are no Availability Zones (like North Central US) and create a Virtual Machine Scale Set with a parameter "zoneBalance" specified. You get the above error. 

Example:
1. Create an ARM deployment with [this ARM template](https://gist.github.com/pbstrein/130c8b6f82360d13ae695e599c9801d9).
2. Add a paramter for the adminPassword (see json snippet below)
3. Run ARM deployment, the error should appear. 
```json
		{
			"adminPassword": {
				"value": "P@ssword1234"
			}
		}

```

## Proposed Solution
Change the API to ignore zoneBalance if one or zero zones are specified. That would lead to a better API consumer experience since otherwise we need to conditionally check whether a region/VM SKU supports Availability Zones to be able to add/remove the zoneBalance parameter as needed.

**Comment by axayjo** [comment] 2020-12-01 08:42
@avirishuv can you please take a look at this issue?

**Comment by pbstrein** [comment] 2020-12-22 15:33
@axayjo, @avirishuv Any word on this issue?

**Comment by amjads1** [comment] 2020-12-23 18:45
Looks like the issue got unassigned automatically. Assigned back to @avirishuv  to look into this issue.

**Comment by avirishuv** [comment] 2021-01-22 19:33
Thanks for the suggestion, @pbstrein Marking this as a bug and will circle back with updates.

**Comment by wangjun-jwa** [comment] 2021-01-23 22:52
zoneBalance can only be set if the vmss contains more than one zones in zones property in VMSS. if there is no zones property in template, zoneBalance should not be set.


zones |   | string[] | The virtual machine scale set zones. NOTE: Availability zones can only be set when you create the scale set
-- | -- | -- | --

**Comment by pbstrein** [comment] 2021-02-01 21:46
@wangjun-jwa 

I would argue that it leads to a poor API consumption experience. To force the API consumer to specify a property based on the existence of another property requires API consumers to have programmatic checking of how many zones are given to a scale set. Since the number of zones is dynamic (varies based on the region and the VM SKU) it may not always be consistent. 

It makes more sense the API check the number of zones, and if there are 1 or 0 zones to _ignore_ the zoneBalance property, instead of forcing API consumers to remove it.

**Comment by wangjun-jwa** [comment] 2021-02-08 19:49
This is the align with other experience like zones property. customer cannot set zones if a region doesn't support it.

**Comment by pbstrein** [comment] 2021-03-05 17:04
If the region does not support it, then why not have the region _ignore_ all properties that are not relevant, rather than error out? 

If someone is working on automation that needs to work in multiple regions, it requires that their automation to do conditional logic on whether to add/remove properties. It makes it easy for a consumer if the properties are ignored (rather than error out) for regions where it isn't supported.

**Comment by avirishuv** [comment] 2021-03-05 17:59
hi @pbstrein, this behavior is by design and in alignment with the API experience for zones and zone balancing. The zoneBalance property can only be set if the zones property of the scale set contains more than one zones. If there is no zones or only one zone specified, then zoneBalance property should not be set.

We will be updating the API docs to make this more clear as well.

**Comment by avirishuv** [comment] 2021-06-09 22:47
Apologies for the delay here, the doc update is still pending, I will confirm here once the doc update is completed.

**Comment by avirishuv** [comment] 2021-09-09 17:53
Property description is updated in API docs: https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-scale-sets/create-or-update

Closing this issue.

**Closed by avirishuv** 2021-09-09 17:53 UTC
Labels: bug, Compute - VMSS, Service Attention
