### ISSUE TITLE
Not able to create a Functions App (App Service Client) with uppercase name

### ISSUE THREAD

**Issue by marstr** [Azure/azure-rest-api-specs#3674] opened 2018-08-20 16:28 UTC
@JunyiYi discovered the following error while using the Azure-SDK-for-Go. However, since the server is responding with an error, I do not believe it is related to the fact  that it is coming from the Go SDK. You can see the original issue here: https://github.com/Azure/azure-sdk-for-go/issues/2482

---

> ## Bug Report
> - import "github.com/Azure/azure-sdk-for-go/services/web/mgmt/2018-02-01/web"
> - Get a client instance of web.AppsClient
> - Try to create a function app resource:
> ``` 
> kind := "functionapp"
> client.CreateOrUpdate(ctx, resGroupName, name, web.Site{
> 	Kind:     &kind,
> 	...
> })
> ```
> - SDK version 18.0.0; go version 1.9.1
> ### Actual Behavior
> Failed to create the resource when name contains uppercase letters.
> 
> ### Expected Behavior
> SDK should not complain about uppercase letters since Azure portal supports them.
> 
> ### Detailed REST API log
> Failed Call (Response is “400 Bad Request, There was a conflict.”):
> 
> ```
> PUT /subscriptions/****/resourceGroups/mcw-serverless-architecture/providers/Microsoft.Web/sites/mcW-tollbooth-events-repro-func-20180817?api-version=2018-02-01 HTTP/1.1
> {
>    "kind": "functionapp",
>     "location": "westus2",
>    "properties": {
>        "enabled": true,
>        "serverFarmId": "/subscriptions/****/resourceGroups/mcw-serverless-architecture/providers/Microsoft.Web/serverfarms/azure-functions-mcw-service-plan",
>        "siteConfig": {
>            "appSettings": [
>                {
>                    "name": "AzureWebJobsDashboard",
>                    "value": "DefaultEndpointsProtocol=https;AccountName=mcwfunctionreprosa;AccountKey=****;EndpointSuffix=core.windows.net"
>                }, {
>                    "name": "AzureWebJobsStorage",
>                    "value": "DefaultEndpointsProtocol=https;AccountName=mcwfunctionreprosa;AccountKey=****;EndpointSuffix=core.windows.net"
>                }, {
>                    "name": "FUNCTIONS_EXTENSION_VERSION",
>                    "value": "~1"
>                }, {
>                    "name": "WEBSITE_CONTENTSHARE",
>                    "value": "mcW-tollbooth-events-repro-func-20180817-content"
>                }, {
>                    "name": "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING",
>                    "value": "DefaultEndpointsProtocol=https;AccountName=mcwfunctionreprosa;AccountKey=****;EndpointSuffix=core.windows.net"
>                }
>            ]
>        },
>        "clientAffinityEnabled": false,
>        "httpsOnly": false
>    },
>    "tags": {}
> }
> ```
>Successful Call (Response is “200 OK”):
> 
> ```
> PUT /subscriptions/****/resourceGroups/mcw-serverless-architecture/providers/Microsoft.Web/sites/mcw-tollbooth-events-repro-func-20180817?api-version=2018-02-01 HTTP/1.1
> {
>    "kind": "functionapp",
>    "location": "westus2",
>    "properties": {
>        "enabled": true,
>        "serverFarmId": "/subscriptions/****/resourceGroups/mcw-serverless-architecture/providers/Microsoft.Web/serverfarms/azure-functions-mcw-service-plan",
>        "siteConfig": {
>            "appSettings": [
>                {
>                    "name": "AzureWebJobsDashboard",
>                    "value": "DefaultEndpointsProtocol=https;AccountName=mcwfunctionreprosa;AccountKey=****;EndpointSuffix=core.windows.net"
>                }, {
>                    "name": "AzureWebJobsStorage",
>                    "value": "DefaultEndpointsProtocol=https;AccountName=mcwfunctionreprosa;AccountKey=****;EndpointSuffix=core.windows.net"
>                }, {
>                    "name": "FUNCTIONS_EXTENSION_VERSION",
>                    "value": "~1"
>                }, {
>                    "name": "WEBSITE_CONTENTSHARE",
>                    "value": "mcw-tollbooth-events-repro-func-20180817-content"
>                }, {
>                    "name": "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING",
>                    "value": "DefaultEndpointsProtocol=https;AccountName=mcwfunctionreprosa;AccountKey=****;EndpointSuffix=core.windows.net"
>                }
>            ]
>        },
>        "clientAffinityEnabled": false,
>        "httpsOnly": false
>    },
>    "tags": {}
> }
> ```

**Comment by JunyiYi** [comment] 2018-08-23 23:03
After talking to internal devs, the problem resides in the `WEBSITE_CONTENTSHARE`, which should not contain upper-case letters. Please close this issue as `By Design`. Thanks.

**Closed** 2018-08-24 20:30 UTC
Labels: App Services, Service-team, wontfix
