### ISSUE TITLE
Ignore existing resources within a subscription

### ISSUE THREAD

**Issue by szaher** [Azure/azure-rest-api-specs#9042] opened 2020-04-13 22:11 UTC
Add flag to cancel subscription request to ignore currently existing (deployed) resources in the subscription to be cancelled.

related to this issue here https://github.com/Azure/azure-sdk-for-python/issues/10814

**Comment by weidongxu-microsoft** [comment] 2020-04-14 00:54
Looks like a feature requirement.

**Comment by szaher** [comment] 2020-04-19 01:50
any updates ?

**Comment by anuragdalmia** [comment] 2020-06-04 22:51
This behavior is currently by design. We explicitly did not enable this to prevent accidental cancellations of subscriptions with active resources that could impact prod services. If you would like to cancel subscriptions, you should be able to delete all resources and then cancel the subscriptions via the APIs. The reason we support this in UX and not in API is that the UX has enough warnings and functionality to review what is being deleted which will not be the case via API.

I will be closing this for now. Please re-open if you disagree and share the functionality that doesnt get addressed by existing APIs.

**Closed by anuragdalmia** 2020-06-04 22:51 UTC
Labels: Service Attention, Subscription
