### ISSUE TITLE
[EventHubs] Support for capturing to Azure Data Lake

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-rest-api-specs#2255] opened 2018-01-11 10:28 UTC
:wave: hello!

I've been working on implementing support for EventHub Capture Descriptions in Terraform.

We've successfully been able to add support for capturing EventHub messages to a Blob Storage Account - however in the process [we've identified in this document](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-resource-manager-namespace-event-hub-enable-capture#resources-to-deploy-for-azure-data-lake-store-as-destination) that it's possible to set a Data Lake as the destination for the captured messages too - however this isn't currently available in the Azure SDK for Go:

https://github.com/Azure/azure-sdk-for-go/blob/master/services/eventhub/mgmt/2017-04-01/eventhub/models.go#L768-L774

So that we're able to support this functionality - would it be possible to add the `DataLakeSubscriptionId`, `DataLakeAccountName` and `DataLakeFolderPath` fields to the Swagger?

Thanks!

cc @vishrutshah @v-Ajnava

**Comment by amenon90** [comment] 2018-11-21 16:07
Any updates with this feature request?

**Comment by tombuildsstuff** [comment] 2019-01-16 16:03
ping @jianghaolu

**Comment by jeroenboeye** [comment] 2019-05-15 13:26
Any progress on this @jianghaolu?

**Comment by patrikdevlin** [comment] 2019-08-21 03:26
This would be great! Any updates @jianghaolu?

**Comment by maxbog** [comment] 2019-10-04 07:48
@jianghaolu Any progress on the issue?

**Comment by d1mnewz** [comment] 2019-10-08 19:10
We need to have this, please take a look @jianghaolu

**Comment by lotaezhao** [comment] 2020-01-03 15:35
Direct capture to Data Lake storage gen2 is needed, I will have to drop back to ARM once again due to half baked resource support in terraform

**Comment by lotaezhao** [comment] 2020-01-03 19:15
I take my previous comment back, you can configure capture with azurerm_eventhub to Data Lake storage gen2 since this is based on Azure Blob storage. I've done this via terraform and it's working. So the issue is only for Data Lake storage gen1 which isn't going to be very common for new deployments anymore.

**Comment by nickzhums** [comment] 2020-03-10 15:18
@josefree  could you help with this and see if we need to take any further action?  thanks

**Comment by jianghaolu** [comment] 2020-03-10 21:43
Removing myself as I don't work on Go, or Event Hubs, or Storage.

**Comment by josefree** [comment] 2020-03-11 09:10
This is a new feature to swagger. @akning-ms Please take a look.

**Comment by vamathan** [comment] 2020-03-11 18:02
Hi Team,

Could you please provide an ETA for this ?

**Comment by josefree** [comment] 2020-03-12 00:21
Hi, this is not only swagger impacted. Series of downstream tools need an update to fulfill this requirement. We do not have a plan on this in this semester, I am afraid.  may set up a plan for next semester.

**Comment by akning-ms** [comment] 2020-03-17 13:28
@tombuildsstuff Sorry for reply late,  routed to eventhub service team for comments

**Comment by tombuildsstuff** [comment] 2020-06-30 09:42
This Swagger bug has been open for 2.5 years now.. is it likely to get fixed anytime soon?

**Comment by jvanenckevort** [comment] 2020-09-02 07:37
Any update on this feature?

**Comment by nickzhums** [comment] 2020-09-02 08:28
@jfggdl could you provide more inforamtion?

**Comment by mcalnd70** [comment] 2021-05-11 07:09
Just been given this as a requirement to code - check docs to find its not supported - 3+ years later - I guess this isn't happening

**Comment by Karl90** [comment] 2021-05-29 10:48
Dear All,

Have you reviewed this key feature?

Note that several large organizations relies on the Data Capture Feature using the Azure DL as the (main) destination for data management.
Since this is possible through the Azure Portal, it sounds fair to add its support on the Azure SDK for Go, in this way we would be able to instrument its configuration in a declarative/automatic way instead of interactive/manual actions. 
The more EHs you have, the more errors are most likely going to happen. In our environment We have more than 100 EHs, so it is not viable to maintain unless we use this feature.

@jfggdl , by any chance, do you have any news around this? 
It's been opened during 3Y, it's not considered at all?

Thanks in advance for your help,

Regards,

Karl.

**Comment by Karl90** [comment] 2021-05-31 14:12
Hi All,

As per Microsoft's inputs, we should also report this through the "feedback" portal.
I've raised [it](https://feedback.azure.com/forums/911458-event-hubs/suggestions/43538361--eventhubs-support-for-capturing-to-azure-data-la), feel free to add your vote.  The more votes we have, the most likely it's going to be implemented.

Note that this is only available on the SDK for .Net and ARM, it sounds fair to have this on the one for GO, but this relies on MS.

regards,

Karl.

**Comment by Karl90** [comment] 2021-06-07 14:03
Hi All,

it turns out that MS give us no ETA to have "this feature" on the SDK for Go, then tf is affected due to this lack of support on the non "main" SDK.

![image](https://user-images.githubusercontent.com/34442949/121030164-86ce4e80-c7a9-11eb-8342-bd95f55c9917.png)

I'd say that the best that we can do is to [vote for it](https://feedback.azure.com/forums/911458-event-hubs/suggestions/43538361--eventhubs-support-for-capturing-to-azure-data-la), so please, feel free to add yours.

I did not expect this scenario, what a bottleneck. 

regards,

Karl.

**Comment by mcalnd70** [comment] 2021-06-07 14:08
I'm slightly concerned long-term about Terraform's reliance on the Go SDK from Microsoft when using it to deploy to Azure. With their "bicep" invention it's disappointing they didn't join up with Terraform to make it better. 

Are we saying that if the Go SDK drops further back and potentially gets retired, Terraform for Azure is over? Even for this request, 3 years in the making and counting...

**Comment by Karl90** [comment] 2021-06-09 12:59
> I'm slightly concerned long-term about Terraform's reliance on the Go SDK from Microsoft when using it to deploy to Azure. With their "bicep" invention it's disappointing they didn't join up with Terraform to make it better.

I'm absolutely agree with you, why not join efforts to produce a reliable solution?

Well, according to[ ms bicep project](https://github.com/Azure/bicep):
![image](https://user-images.githubusercontent.com/34442949/121357545-2dddf200-c932-11eb-8286-c2fcd6a48b5f.png)
They're investing as much as possible to provide us the best experience possible while using tf :-)

From my perspective the issue is not only this problem but the potential ones that I might find while digging deeper with another resources,
the issue is actually introduced by MS because of the lack of proper maintenance on this SDK; tf just relies on it.

Instead of doing that, MS invest on bicep which is "fully" supported by them (and is fair to do so) but the maintenance on the SDKs used by third party products is a must, and this case is an example of lack of support on it.

Unfortunately, the best that we can do is just to submit through the feedback portal .. which is awkward, they have this issue opened during 3Y ..

regards,

Karl.

**Comment by FredrikAugust** [comment] 2022-01-06 14:40
Any updates here?

**Comment by snugghash** [comment] 2022-02-08 19:30
Is there a way we can pool money to pay for this feature for a team at Azure to build it out?

**Comment by Saglodha** [comment] 2022-11-22 06:20
Closing the issue since properties have been added to swagger file. Please feel free to reach out in case of any queries.

**Comment by Saglodha** [comment] 2022-11-22 06:20
Closing issue since properties have been added to swagger: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/eventhub/resource-manager/Microsoft.EventHub/stable/2021-11-01/eventhubs.json

**Closed by Saglodha** 2022-11-22 06:20 UTC
Labels: Event Hubs, Service Attention
